namespace AT.Core.ResearchQG;

/// <summary>QG-099 origin-of-H model: catalog of H-origin mechanisms and whether H can be
/// calculated from {c, G, ħ, Λ, N} without circularity. The Planck rate 1/t_P = c/l_P is ~61
/// decades too large; H ~ c√Λ is circular (Λ ~ H²/c²); H from N is circular (N defined by H).</summary>
public sealed record HOrigin(string Model, string Mechanism, string Classification, bool Circular, string Verdict);

public static class OriginOfHModel
{
    public const double C = 299792458.0;
    public const double G = 6.674e-11;
    public const double Hbar = 1.054571817e-34;
    public const double H0 = 67.4;
    public const double Lambda = 1.1e-52;
    public const double Kpc_m = 3.0857e19;

    public static double H0PerS => H0 / Kpc_m;                       // 2.184e-18 s^-1
    public static double PlanckLength => Math.Sqrt(Hbar * G / (C * C * C));
    public static double PlanckRate => C / PlanckLength;             // 1/t_P ~ 1.85e43 s^-1
    public static double HRateFromLambda => C * Math.Sqrt(Lambda);   // ~3.1e-18 s^-1 (~H0)

    /// <summary>H from {c, G, ħ}: only 1/t_P, wrong by ~61 decades.</summary>
    public static double PlanckHierarchy => Math.Log10(PlanckRate / H0PerS);

    /// <summary>H from Λ: c√Λ ≈ H0 (but Λ ~ H²/c² is itself H-dependent → circular).</summary>
    public static double HRateFromLambdaRatio => HRateFromLambda / H0PerS;

    /// <summary>Catalog of H origins.</summary>
    public static HOrigin[] Origins() => new[]
    {
        new HOrigin("FLRW (ȧ/a)", "H is the initial condition of the Friedmann equation",
            "Input (boundary condition)", false, "H0 not predicted — it is set by initial data"),
        new HOrigin("Inflation", "H ~ V(φ)^1/2 dynamically generated by the inflaton",
            "Dynamically generated", false, "H_early derived, but V(φ) is tuned; H_today set by reheating"),
        new HOrigin("de Sitter", "H = √(Λ/3), so H from Λ",
            "Derived from Λ", true, "circular: Λ ~ H²/c² (causal set), so H from Λ is H from H"),
        new HOrigin("Causal set", "N = (c/H l_P)⁴ defines N; H is the input",
            "Input", true, "H defines N; H is not derived from N (QG-098)"),
        new HOrigin("Anthropic", "H selected among vacua; only Λ is anthropically fixed",
            "Selection", false, "selects Λ (and hence H~c√Λ), not H's specific value"),
        new HOrigin("Fundamental constant", "H0 is a new dimensionful constant",
            "Primitive", false, "1 new parameter, no derivation"),
    };
}
