namespace AT.App.Models;

// ── Docs/ATQG_PredictionOutcomes.json ────────────────────────────────────

public sealed record PredictionOutcomeFile(
    OutcomeMeta Meta,
    List<PredictionOutcomeModel> Outcomes);

public sealed record OutcomeMeta(
    string Title,
    string Purpose,
    List<string> States,
    string RegistryRule,
    string LockedBy,
    string LastUpdated);

public sealed record PredictionOutcomeModel(
    string Id,
    string Name,
    string State,
    string FrozenValue,
    string CurrentEvidence,
    string SupportLevel,
    string LastAudit,
    string NextExperiment,
    string Falsification);

// ── Docs/ATQG_Predictions.json ────────────────────────────────────────────

public sealed record PredictionRegistryFile(
    string Title,
    bool Immutable,
    string Rule,
    string LockedBy,
    List<RegisteredPredictionModel> Predictions);

public sealed record RegisteredPredictionModel(
    string Id,
    string Name,
    string DerivationPhase,
    string Formula,
    string Inputs,
    string FrozenValue,
    string Uncertainty,
    string Falsification,
    string? Outcome);

// ── Docs/ATQG_PhysicsCoverage.json ────────────────────────────────────────

public sealed record PhysicsCoverageFile(
    CoverageMeta Meta,
    CoverageStats Coverage,
    List<ContradictionModel> Contradictions,
    List<OpenQuestionModel> OpenQuestions,
    List<CoveragePredictionModel> Predictions,
    List<ObservableModel> Observables,
    List<GrTopicModel> GrTopics,
    List<RecentFindingModel> RecentFindings,
    List<PhaseModel> Phases);

public sealed record CoverageMeta(
    string File,
    string Purpose,
    string LastUpdated,
    int PhasesCount,
    string Note);

public sealed record CoverageStats(
    int TotalPhases,
    int Tested,
    int Partial,
    int Untested,
    int Audit,
    double WeightedCoverage,
    Dictionary<string, DomainStats>? Domains,
    Dictionary<string, int>? Observables);

public sealed record DomainStats(int Tested, int Partial, int Untested, int Audit, int Total);

public sealed record ContradictionModel(
    string Id,
    string Topic,
    string A,
    string B,
    string Status,
    string? Resolution,
    List<string>? Phases);

public sealed record OpenQuestionModel(
    string Question,
    string Phase,
    string Status);

public sealed record CoveragePredictionModel(
    string Prediction,
    string Phase,
    string Status);

public sealed record ObservableModel(
    string Name,
    string Status,
    string Phase,
    string Detail);

public sealed record GrTopicModel(
    string Topic,
    string Phase,
    string Status,
    string Detail);

/// <summary>A recent finding (the latest N phases, generated by the coverage script).</summary>
public sealed record RecentFindingModel(
    double Phase,
    string? PhaseLabel,
    string File,
    string Title,
    string Classification,
    string Domain,
    string Validation,
    string Summary,
    string ReportUrl);

public sealed record PhaseModel(
    double Phase,
    string File,
    string Classification,
    string Domain,
    string Validation,
    string KeyResult);
