namespace TQM.Core.ResearchXH;

/// <summary>
/// TQM-QG Phase 0 — unify actualization dynamics and gravity. Builds the bridge from the microscopic
/// actualization rule (Q-event generation, entropy-maximized scale-free abundance) to the radial density ρ
/// that the gravity program requires, and verifies that this single ρ reproduces the metric origin, deficit
/// matter, Einstein structure, and flat rotation curves. No new primitives.
/// </summary>
public static class ActualizationGravity
{
    /// <summary>Entropy-maximized (α=0) per-octave allocation: uniform increments A_k = m₀/K.</summary>
    public static double[] EntropyMaximizedIncrements(double m0, int K)
    {
        var a = new double[K];
        for (int k = 0; k < K; k++) a[k] = m0 / K;
        return a;
    }

    /// <summary>Cumulative deficit at octave k: m_k = Σ_{j≥k} A_j = m₀(K−k)/K.</summary>
    public static double CumulativeDeficit(double[] increments, int k)
    {
        double s = 0.0;
        for (int j = k; j < increments.Length; j++) s += increments[j];
        return s;
    }

    /// <summary>
    /// Continuum actualization density from the α=0 attractor: ρ = ρ̄ − m₀·ln(Rmax/r)/ln(Rmax/r₀)
    /// (the log-deficit density, the flat-rotation-curve profile generated by entropy maximization).
    /// </summary>
    public static double ActualizationDensity(double r, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0)
        => DeficitCollective.LogDeficit(r, rhoBar, m0, r0, Rmax);

    /// <summary>Deficit matter m = ρ̄ − ρ (positive in the deficit region r &lt; Rmax).</summary>
    public static double DeficitMatter(double r, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0)
        => rhoBar - ActualizationDensity(r, m0, r0, Rmax, rhoBar);

    /// <summary>ρ′ from the actualization density (central difference).</summary>
    public static double RhoPrime(double r, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0, double h = 1e-5)
        => (ActualizationDensity(r + h, m0, r0, Rmax, rhoBar) - ActualizationDensity(r - h, m0, r0, Rmax, rhoBar)) / (2.0 * h);

    /// <summary>ρ″ from the actualization density (central difference).</summary>
    public static double RhoSecond(double r, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0, double h = 1e-5)
        => (ActualizationDensity(r + h, m0, r0, Rmax, rhoBar) - 2.0 * ActualizationDensity(r, m0, r0, Rmax, rhoBar) + ActualizationDensity(r - h, m0, r0, Rmax, rhoBar)) / (h * h);

    /// <summary>Einstein tensor x-component G_11 from the actualization density (direct ρ-form).</summary>
    public static double Einstein11FromDensity(double r, int d, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0)
        => HigherDimEinstein.DirectEinstein11(ActualizationDensity(r, m0, r0, Rmax, rhoBar), RhoPrime(r, m0, r0, Rmax, rhoBar), d);

    /// <summary>Einstein tensor transverse component G_ii from the actualization density (direct ρ-form).</summary>
    public static double EinsteinOtherFromDensity(double r, int d, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0)
        => HigherDimEinstein.DirectEinsteinOther(ActualizationDensity(r, m0, r0, Rmax, rhoBar), RhoPrime(r, m0, r0, Rmax, rhoBar), RhoSecond(r, m0, r0, Rmax, rhoBar), d);

    /// <summary>Rotation-curve ratio v²(r1)/v²(r2) for the actualization density (≈1 ⇒ flat).</summary>
    public static double RotationCurveRatio(double r1, double r2, int d = 3, double m0 = 0.4, double r0 = 0.5, double Rmax = 10.0, double rhoBar = 1.0)
        => DeficitCollective.RotationCurveProxy(u => ActualizationDensity(u, m0, r0, Rmax, rhoBar), r1, d)
         / DeficitCollective.RotationCurveProxy(u => ActualizationDensity(u, m0, r0, Rmax, rhoBar), r2, d);
}
