namespace TQM.Core.ResearchXH;

/// <summary>
/// TQM-QG Phase 17 — unfreeze the tensor sector. Tests whether the scalar actualization (counting measure ρ) can
/// source the tensor/graviton (ψ) mode, or whether a non-scalar (tensor) primitive is required. The Weyl tensor is
/// conformally invariant, so a scalar ρ can NEVER source it. No new primitives.
/// </summary>
public static class UnfreezeTensor
{
    /// <summary>Traceless (tensor) part of the metric fluctuation generated by a SCALAR source δρ — identically zero.</summary>
    public static double TensorPartFromScalarSource(double N, int d)
        => SpacetimeFluctuations.MetricFluctuationTraceless(N, d);

    /// <summary>Frozen tensor (Weyl) degrees of freedom that a tensor source must excite (10 at d=3).</summary>
    public static double FrozenTensorDof(int d) => DimensionAnalysis.WeylComponents(d);

    /// <summary>Degrees of freedom of the scalar counting measure ρ (always 1).</summary>
    public static double ScalarDof() => 1.0;
}
