namespace TQM.Core.ResearchXH;

/// <summary>
/// TQM-QG Phase 155 — Origin of the Z2 doublet symmetry. QG153 established that the observable-sector
/// spectrum is fully Z2-paired (95/95 modes in degenerate doublets) and identified the reflection and
/// half-shift automorphisms of the 12-regular adjacency as the symmetry origin. This phase asks: WHY does
/// the observable sector possess the Z2 symmetry that generates the doublets? Is it ACCIDENTAL (an
/// artifact of the particular seed), DYNAMICAL (generated by the attractor dynamics), or a genuine
/// symmetry-origin?
///
/// Method (computational, fully deterministic): (1) REFLECTION SYMMETRY — invariance of the seed vs the
/// final adjacency under i → n−1−i; (2) HALF-SHIFT SYMMETRY — invariance under i → i+n/2 (period-3 seed
/// with 3 | n); (3) ATTRACTOR DYNAMICS — the symmetry emergence during evolution: the dynamics create
/// links to CYCLIC neighbors (i+d) mod n, generating a circulant ring; (4) OCTAVE-BAND STRUCTURE — the
/// family bands of the resulting spectrum; (5) SYMMETRY SELECTION — the full automorphism group of the
/// converged circulant C_n(1..k): rotation group Z_n and reflection (dihedral D_n), whose 2D irreducible
/// representations generate the Z2 doublets.
///
/// Answer (determined by the computed data): [filled by Classify]. No new primitives added here.
/// </summary>
public static class Z2SymmetryOrigin
{
    /// <summary>Tolerance for adjacency invariance checks.</summary>
    public const double InvarianceTolerance = 1e-12;

    /// <summary>Default network size.</summary>
    public const int DefaultN = 96;

    // ── Permutation helpers ─────────────────────────────────────────────────────

    /// <summary>Reflection permutation σ(i) = n − 1 − i.</summary>
    public static int[] ReflectionPermutation(int n)
    {
        var s = new int[n];
        for (int i = 0; i < n; i++) s[i] = n - 1 - i;
        return s;
    }

    /// <summary>Half-shift permutation σ(i) = (i + n/2) mod n.</summary>
    public static int[] HalfShiftPermutation(int n)
    {
        var s = new int[n];
        for (int i = 0; i < n; i++) s[i] = (i + n / 2) % n;
        return s;
    }

    /// <summary>Rotation permutation σ(i) = (i + s) mod n.</summary>
    public static int[] RotationPermutation(int n, int shift)
    {
        var s = new int[n];
        for (int i = 0; i < n; i++) s[i] = (i + shift) % n;
        return s;
    }

    /// <summary>Is the adjacency invariant under the permutation σ?</summary>
    public static bool InvariantUnder(double[,] a, int[] sigma)
    {
        int n = a.GetLength(0);
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
                if (Math.Abs(a[i, j] - a[sigma[i], sigma[j]]) > InvarianceTolerance) return false;
        return true;
    }

    /// <summary>Is a vector invariant under the permutation σ?</summary>
    public static bool VectorInvariant(double[] v, int[] sigma)
    {
        for (int i = 0; i < v.Length; i++)
            if (Math.Abs(v[i] - v[sigma[i]]) > InvarianceTolerance) return false;
        return true;
    }

    // ── 1. Reflection symmetry ──────────────────────────────────────────────────

    /// <summary>Is the SEED activity pattern reflection-invariant?</summary>
    public static bool SeedReflectionSymmetry()
        => VectorInvariant(EnergyDependentAttractors.EnergyScaledSeed(DefaultN, 1.0),
            ReflectionPermutation(DefaultN));

    /// <summary>Is the FINAL observable-sector adjacency reflection-invariant?</summary>
    public static bool AdjacencyReflectionSymmetry()
    {
        var (_, adj) = HighEnergySectorStability.ObservableSector();
        return InvariantUnder(adj, ReflectionPermutation(adj.GetLength(0)));
    }

    /// <summary>Does the reflection symmetry ORIGINATE in the attractor dynamics (not the seed)?</summary>
    public static bool ReflectionFromDynamics()
        => !SeedReflectionSymmetry() && AdjacencyReflectionSymmetry();

    // ── 2. Half-shift symmetry ──────────────────────────────────────────────────

    /// <summary>Is the SEED activity pattern half-shift-invariant (period 3 with 3 | n)?</summary>
    public static bool SeedHalfShiftSymmetry()
        => VectorInvariant(EnergyDependentAttractors.EnergyScaledSeed(DefaultN, 1.0),
            HalfShiftPermutation(DefaultN));

    /// <summary>Is the FINAL adjacency half-shift-invariant?</summary>
    public static bool AdjacencyHalfShiftSymmetry()
    {
        var (_, adj) = HighEnergySectorStability.ObservableSector();
        return InvariantUnder(adj, HalfShiftPermutation(adj.GetLength(0)));
    }

    /// <summary>Does the half-shift symmetry ORIGINATE in the seed's period-3 pattern?</summary>
    public static bool HalfShiftFromSeed()
        => SeedHalfShiftSymmetry() && AdjacencyHalfShiftSymmetry();

    // ── 3. Attractor dynamics ───────────────────────────────────────────────────

    /// <summary>
    /// Symmetry emergence during attractor evolution: (steps, reflection, halfShift, regular, degree) for
    /// the adjacency after `steps` dynamics iterations. The dynamics create links to cyclic neighbors
    /// (i+d) mod n, generating a circulant ring; the symmetries emerge as the attractor saturates.
    /// </summary>
    public static (int Steps, bool Reflection, bool HalfShift, bool Regular, int Degree)[]
        SymmetryEmergence()
    {
        int n = DefaultN;
        var result = new List<(int, bool, bool, bool, int)>();
        foreach (int steps in new[] { 1, 2, 3, 5, 10, 20, 40, 80, 120, 160, 200 })
        {
            var dyn = EnergyDependentAttractors.AdaptiveNetworkWithDecayFull(
                EnergyDependentAttractors.EnergyScaledSeed(n, 1.0), 6, 0.3, 0.9, steps, 1.0, 0.5);
            var adj = dyn.Adjacency;
            bool refl = InvariantUnder(adj, ReflectionPermutation(n));
            bool shift = InvariantUnder(adj, HalfShiftPermutation(n));
            int deg0 = 0;
            for (int j = 0; j < n; j++) deg0 += (int)adj[0, j];
            bool regular = true;
            for (int i = 0; i < n && regular; i++)
            {
                int d = 0;
                for (int j = 0; j < n; j++) d += (int)adj[i, j];
                if (d != deg0) regular = false;
            }
            result.Add((steps, refl, shift, regular, deg0));
        }
        return result.ToArray();
    }

    /// <summary>
    /// Does the attractor converge to a fully symmetric state (both symmetries present at step ≥ 5 and
    /// stable through step 200)?
    /// </summary>
    public static bool AttractorConvergesSymmetric()
    {
        var em = SymmetryEmergence();
        // both symmetries present by step 5 and stable through the end
        bool early = em.First(e => e.Steps == 5).Reflection && em.First(e => e.Steps == 5).HalfShift;
        bool late = em.Last().Reflection && em.Last().HalfShift;
        return early && late;
    }

    // ── 4. Octave-band structure ────────────────────────────────────────────────

    /// <summary>Octave bands of the observable sector: (band, modes, localWeyl).</summary>
    public static (int Band, int Modes, double LocalWeyl)[] OctaveBands()
        => ModeAccessOrigin.OctaveBandStructure();

    /// <summary>Family count (number of octave bands).</summary>
    public static int FamilyCount()
        => ModeAccessOrigin.BandOccupancies().Length;

    /// <summary>Is the 3-family octave structure present (bands ≥ 3)?</summary>
    public static bool ThreeFamilies()
        => FamilyCount() >= 3;

    // ── 5. Symmetry selection (circulant ring) ──────────────────────────────────

    /// <summary>
    /// Is the adjacency CIRCULANT (rotationally invariant: adj[i,j] depends only on (j−i) mod n)? The
    /// circulant ring C_n(1..k) has the full rotation symmetry Z_n.
    /// </summary>
    public static bool IsCirculant()
    {
        var (_, adj) = HighEnergySectorStability.ObservableSector();
        int n = adj.GetLength(0);
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
            {
                int d = (j - i + n) % n;
                if (Math.Abs(adj[i, j] - adj[0, d]) > InvarianceTolerance) return false;
            }
        return true;
    }

    /// <summary>
    /// Is every rotation shift s a symmetry of the adjacency (full rotation group Z_n)? Returns the
    /// count of invariant shifts among {1..n}.
    /// </summary>
    public static int RotationSymmetryCount()
    {
        var (_, adj) = HighEnergySectorStability.ObservableSector();
        int n = adj.GetLength(0);
        int count = 0;
        foreach (int s in new[] { 1, 2, 3, 6, 8, 12, 16, 24, 32, 48, 96 })
            if (s <= n && InvariantUnder(adj, RotationPermutation(n, s))) count++;
        return count;
    }

    /// <summary>Connection radius k of the circulant C_n(1..k).</summary>
    public static int ConnectionRadius()
    {
        var (_, adj) = HighEnergySectorStability.ObservableSector();
        int n = adj.GetLength(0);
        int k = 0;
        for (int j = 1; j < n && adj[0, j] != 0.0; j++) k = j;
        return k;
    }

    /// <summary>
    /// The symmetry-selection mechanism: the dynamics generate a circulant ring C_n(1..k) with dihedral
    /// automorphism group D_n (all rotations + reflection), whose 2D irreducible representations generate
    /// the Z2 doublets. Holds if the adjacency is circulant with both Z2 symmetries.
    /// </summary>
    public static bool SymmetrySelectionMechanism()
        => IsCirculant() && AdjacencyReflectionSymmetry() && AdjacencyHalfShiftSymmetry();

    // ── Origin score & classification ───────────────────────────────────────────

    /// <summary>
    /// Z2-symmetry-origin score (0..5):
    /// 1. the reflection symmetry ORIGINATES in the dynamics (absent in the seed, present in the final
    ///    adjacency);
    /// 2. the half-shift symmetry originates in the seed's period-3 pattern (present in both);
    /// 3. the attractor converges to a fully symmetric 12-regular state (both symmetries, step 5 → 200);
    /// 4. the 3-family octave-band structure is present;
    /// 5. the symmetry-selection mechanism holds (circulant ring with rotation + reflection = D_n).
    /// </summary>
    public static int OriginScore()
    {
        int score = 0;
        if (ReflectionFromDynamics()) score++;
        if (HalfShiftFromSeed()) score++;
        if (AttractorConvergesSymmetric()) score++;
        if (ThreeFamilies()) score++;
        if (SymmetrySelectionMechanism()) score++;
        return score;
    }

    /// <summary>
    /// Data-driven classification:
    ///   ACCIDENTAL     — the Z2 symmetries are artifacts of the particular seed, absent or unstable
    ///                    under the dynamics;
    ///   DYNAMICAL      — the symmetries emerge from the attractor dynamics but without a structural
    ///                    selection mechanism;
    ///   SYMMETRY ORIGIN — the Z2 doublet symmetry is a genuine, dynamically-selected property: the
    ///                    attractor dynamics generate a circulant ring C_n(1..k) with dihedral symmetry
    ///                    D_n (rotation Z_n + reflection); the reflection arises from the dynamics
    ///                    (not the seed), the half-shift from the period-3 seed, and the 2D irreducible
    ///                    representations of D_n generate the Z2 doublets — the symmetry origin of the
    ///                    weak-isospin doublet structure.
    /// </summary>
    public static string Classify()
    {
        int score = OriginScore();
        if (score <= 2) return "ACCIDENTAL";
        if (score == 5) return "SYMMETRY ORIGIN";
        return "DYNAMICAL";
    }
}
