using System.Globalization;

using System.Text;

using AT.Core.ResearchXH;

using static AT.Core.ResearchXH.SectorSelectionAudit;

using AT.Tests.Shared;



namespace AT.Tests.ResearchY.E_Electromagnetism;



/// <summary>

/// ResearchY-E_014 - Sector Selection Audit (group E - Electromagnetism).

///

/// QUESTION. What selects the flux sector label n? Known: n exists, n is quantised, n survives refinement. Unknown:

/// why n != 0? Candidates: boundary conditions, topological constraints, actualization process, initial conditions,

/// occupancy arrangement. Goal: locate the ORIGIN OF SECTOR OCCUPATION.

///

/// ANSWER: **BOUNDARY - and the negative is proved rather than declared.** The family is generated by ONE operation

/// (adding a quantum of uniform field to a compact phase), no AT law depends on the sector, the constraint permits

/// every value, and no operation of the configuration space takes a non-zero label to zero. So "why n != 0" has the

/// same status as "why n = 0": neither is selected, and the occupation is an external assignment.

/// </summary>

public class Y_E_014_Tests : ResearchTestBase

{

    public Y_E_014_Tests(ITestOutputHelper o) : base(o) { }



    [Fact]

    public void Y_E_014_TheLabelExistsIsQuantisedAndSurvivesRefinement()

    {

        // n exists and is read the way a measurement would read it

        var a = UniformSector(2, 16);

        Assert.Equal(2.0, SectorLabel(a, 16), 9);

        Assert.True(UniformityResidual(a, 16) < 1e-12, $"uniformity {UniformityResidual(a, 16):E3}");



        // n is quantised: the shift moves the label by one, and the compact phase is what makes it legitimate

        Assert.Equal(1, ShiftMovesTheLabelByOne(0, 16));

        Assert.Equal(1, ShiftMovesTheLabelByOne(7, 16));

        Assert.True(ShiftPhasePeriodicityResidual() < 1e-15, $"phase residual {ShiftPhasePeriodicityResidual():E3}");

        Assert.True(ShiftRealPeriodicityResidual() > 6.0, $"real residual {ShiftRealPeriodicityResidual():F6}");



        // n survives refinement while the strength does not

        var series = LabelSurvivesRefinement();

        Assert.Equal(4, series.Length);

        Assert.All(series, t => Assert.Equal(1.0, t.Label, 9));

        Assert.True(series[0].Strength > series[^1].Strength, $"strength {series[0].Strength:F6} vs {series[^1].Strength:F6}");

        Assert.True(TheLabelSurvivesRefinement(), "labels: " + string.Join(", ", series.Select(t => $"{t.L}:{t.Label:F9}")));

    }



    [Fact]

    public void Y_E_014_OneOperationGeneratesTheWholeFamily()

    {

        var series = VacuumToSectorSeries();

        Assert.Equal(4, series.Length);

        for (int k = 0; k < series.Length; k++)

            Assert.Equal((double)k, series[k].Label, 9);

        Assert.True(OneOperationGeneratesTheFamily());



        // and the operation is invertible, so the sectors are one orbit and not a random walk

        Assert.True(ShiftInvertibilityResidual() < 1e-12);

    }



    [Fact]

    public void Y_E_014_NoATLawDependsOnTheSector()

    {

        var table = SectorBlindnessTable();

        Assert.Equal(4, table.Length);

        Assert.All(table, r => Assert.True(r.Difference < 1e-12, $"{r.Law} differed by {r.Difference:E3}"));

        Assert.True(EveryATLawIsSectorBlind());

        Assert.True(SectorBlindnessResidual() < 1e-12);



        // the occupancy contribution is identical in both sectors - linearity, measured

        Assert.Equal(OccupancyContributionToCurvature(0, 8), OccupancyContributionToCurvature(1, 8), 12);



        // the control: the sector IS visible to a curvature measurement

        Assert.True(Control_TheSectorIsVisible() > 0.5);

    }



    [Fact]

    public void Y_E_014_TheConstraintPermitsEverySector()

    {

        var across = ConstraintAcrossSectors();

        Assert.Equal(7, across.Length);

        Assert.All(across, t => Assert.True(t.Residual < 1e-12, $"n = {t.N} residual {t.Residual:E3}"));

        Assert.True(TheConstraintPermitsEverySector());



        // at several lattice sizes too - the constraint never restricts the uniform family

        foreach (int l in LatticeSizes())

            foreach (int n in new[] { -2, -1, 0, 1, 2 })

                Assert.True(ConstraintResidualForSector(n, l) < 1e-12);

    }



    [Fact]

    public void Y_E_014_NoOperationCollapsesANonZeroSectorToZero()

    {

        var table = OperationTable();

        Assert.Equal(5, table.Length);

        Assert.All(table, t => Assert.True(Math.Abs(t.Label) > 0.5, $"{t.Operation} produced {t.Label:F6}"));

        Assert.True(NoOperationCollapsesTheSectorToZero());



        // translation preserves the label; reflection and negation reverse its sign

        Assert.Equal(1.0, table[0].Label, 9);

        Assert.Equal(1.0, table[1].Label, 9);

        Assert.Equal(1.0, table[2].Label, 9);

        Assert.Equal(-1.0, table[3].Label, 9);

        Assert.Equal(-1.0, table[4].Label, 9);

        Assert.Equal(2, OperationsThatChangeTheLabel().Length);

    }



    [Fact]

    public void Y_E_014_ThreeAreRefutedTwoAreBoundaryAndTheVerdictIsBoundary()

    {

        Assert.Equal(5, Candidates().Length);

        Assert.Equal(3, RefutedCandidates().Length);

        Assert.Contains("topological constraints", RefutedCandidates());

        Assert.Contains("actualization process", RefutedCandidates());

        Assert.Contains("occupancy arrangement", RefutedCandidates());



        Assert.Equal(2, BoundaryCandidates().Length);

        Assert.Contains("boundary conditions", BoundaryCandidates());

        Assert.Contains("initial conditions", BoundaryCandidates());

        Assert.Equal("an external assignment", TheOriginOfSectorOccupation());



        Assert.Equal("BOUNDARY", Verdict());

    }



    [Fact]

    public void Y_E_014_Run()

    {

        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;

        var sb = new StringBuilder();

        PrintHeader("Y_E_014 - Sector Selection Audit: what selects the flux sector label n?");



        sb.AppendLine("QUESTION. What selects the flux sector label n, and why is n != 0?");

        sb.AppendLine("KNOWN        n exists | n is quantised | n survives refinement (E_011, E_012)");

        sb.AppendLine("CANDIDATES   boundary conditions | topological constraints | actualization process |");

        sb.AppendLine("             initial conditions | occupancy arrangement");

        sb.AppendLine("GOAL         locate the origin of sector occupation");

        sb.AppendLine();

        sb.AppendLine("ASSUMPTIONS");

        sb.AppendLine("  1. The label is what a measurement reads: the uniform strength in units of the quantum 2 pi / L.");

        sb.AppendLine("  2. A sector is uniform, so the label does not depend on where it is read - checked, not assumed.");

        sb.AppendLine("  3. The link variable is a COMPACT phase, so a change adding 2 pi at the far end is legitimate even");

        sb.AppendLine("     though the real field is not periodic - the distinction E_011's quantisation rests on.");

        sb.AppendLine("  4. Sector-blindness is measured through linearity of the plaquette in the link field.");

        sb.AppendLine("  5. Deterministic throughout; no randomness.");

        sb.AppendLine();



        PrintHeader(OutputTheLabel());

        PrintHeader(OutputBlindness());

        PrintHeader(OutputOperations());

        PrintHeader(OutputCandidates());

        PrintHeader(OutputVerdict());



        Output.WriteLine(sb.ToString());

    }

}

