using System.Globalization;
using System.Text;
using TQM.Core.ResearchXH;
using TQM.Tests.Shared;
using Xunit.Abstractions;

namespace TQM.Tests.ResearchXH;

/// <summary>
/// G4-RHO Phase 2 — search for a dynamical equation for ρ. G4-RHO1 showed α=0 is the unique maximum-entropy
/// allocation. Here we test whether ρ is GENERATED by a native actualization dynamics (entropy gradient flow,
/// scale-space diffusion) whose stable attractor is α=0, rather than being supplied as input.
///
/// Tests: G4-RHO20 (entropy gradient flow), G4-RHO21 (scale-space diffusion), G4-RHO22 (attractor +
///        classification).
/// </summary>
public class G4RHO_Phase2_EvolutionEquationTests : ResearchTestBase
{
    public G4RHO_Phase2_EvolutionEquationTests(ITestOutputHelper o) : base(o) { }

    private const int K = 8;
    private const double LAMBDA = 1.5;

    // ── G4-RHO20: entropy gradient flow dα/dt = μ·∂H/∂α → α=0 ────────────────────────

    [Fact]
    public void G4_RHO20_EntropyGradientFlow()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("G4-RHO20: entropy gradient flow dα/dt = μ·∂H/∂α has α=0 as its attractor");

        sb.AppendLine($"{"α",7} {"∂H/∂α",12}");
        double d0 = 0, d05 = 0, dm05 = 0;
        foreach (double a in new[] { -1.0, -0.5, 0.0, 0.5, 1.0 })
        {
            double d = RhoDynamics.EntropyDerivative(a, K, LAMBDA);
            if (a == 0.0) d0 = d;
            if (a == 0.5) d05 = d;
            if (a == -0.5) dm05 = d;
            sb.AppendLine($"{a,7:F1} {d,12:F6}");
        }
        double d2 = RhoDynamics.EntropySecondDerivative(0.0, K, LAMBDA);

        // Gradient flow simulation: α_{n+1} = α_n + μ·∂H/∂α.
        double alpha = 1.0;
        for (int i = 0; i < 500; i++) alpha += 0.05 * RhoDynamics.EntropyDerivative(alpha, K, LAMBDA);

        bool criticalPoint = Math.Abs(d0) < 1e-6;
        bool flowDirection = d05 < 0 && dm05 > 0;          // α>0 flows down, α<0 flows up
        bool stableMaximum = d2 < 0;                        // H concave at α=0
        bool converges = Math.Abs(alpha) < 1e-6;

        sb.AppendLine();
        sb.AppendLine($"∂H/∂α(0) = {d0:E2} (critical point: {criticalPoint})");
        sb.AppendLine($"∂H/∂α(±0.5) opposite signs (flow toward 0): {flowDirection}");
        sb.AppendLine($"∂²H/∂α²(0) = {d2:F3} < 0 (stable maximum): {stableMaximum}");
        sb.AppendLine($"gradient flow α(0)=1 → α(500) = {alpha:E2} (→ 0): {converges}");
        sb.AppendLine();
        sb.AppendLine("CONCLUSION: the native evolution equation dα/dt = μ·∂H/∂α (entropy gradient flow) has");
        sb.AppendLine("α=0 as its unique STABLE attractor — the abundance-law exponent relaxes to maximum entropy.");
        Output.WriteLine(sb.ToString());

        Assert.True(criticalPoint, "α=0 should be a critical point of H");
        Assert.True(flowDirection, "∂H/∂α should push α toward 0");
        Assert.True(stableMaximum, "α=0 should be a maximum (∂²H/∂α² < 0)");
        Assert.True(converges, "gradient flow should relax α to 0");
    }

    // ── G4-RHO21: scale-space diffusion → uniform (α=0) fixed point ──────────────────

    [Fact]
    public void G4_RHO21_ScaleSpaceDiffusion()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("G4-RHO21: scale-space diffusion ∂_t A_k = D·Δ_k A_k → uniform (α=0)");

        var A = RhoDynamics.Increments(1.0, K, LAMBDA);      // biased α=1
        double total0 = A.Sum();
        sb.AppendLine($"initial A_k (α=1): [{string.Join(", ", A.Select(x => x.ToString("F3")))}]");
        for (int i = 0; i < 3000; i++) A = RhoDynamics.DiffuseStep(A, 0.4);
        sb.AppendLine($"final   A_k:       [{string.Join(", ", A.Select(x => x.ToString("F4")))}]");

        double uniformity = (A.Max() - A.Min()) / A.Average();
        bool conserved = Math.Abs(A.Sum() - total0) < 1e-9;
        bool uniform = uniformity < 1e-9;

        sb.AppendLine();
        sb.AppendLine($"final uniformity (max−min)/mean = {uniformity:E2} (→ uniform): {uniform}");
        sb.AppendLine($"total deficit conserved: {conserved}");
        sb.AppendLine();
        sb.AppendLine("CONCLUSION: the native flow equation ∂_t A_k = D·(A_{k+1}−2A_k+A_{k−1}) (scale-space diffusion)");
        sb.AppendLine("equilibrates the per-octave deficit toward uniformity while conserving total deficit — the");
        sb.AppendLine("uniform fixed point A_k = const is exactly α=0 (the log-deficit hierarchy).");
        Output.WriteLine(sb.ToString());

        Assert.True(uniform, "scale-space diffusion should converge to the uniform fixed point");
        Assert.True(conserved, "scale-space diffusion should conserve total deficit");
    }

    // ── G4-RHO22: attractor → log-deficit profile; classification ────────────────────

    [Fact]
    public void G4_RHO22_AttractorClassification()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("G4-RHO22: the uniform fixed point is the log-deficit profile — classification");

        // Uniform per-octave increments A_k = const give a cumulative deficit m_k = Σ_{j≥k} A_j ∝ (K−k),
        // which equals ln(Rmax/R_k) (logarithmic deficit, α=0) since K−k = ln(Rmax/R_k)/ln λ.
        double r0 = 0.5, Rmax = r0 * Math.Pow(LAMBDA, K);
        var A = RhoDynamics.Increments(0.0, K, LAMBDA);      // uniform
        sb.AppendLine($"{"octave",7} {"m_k=ΣA_j",12} {"ln(Rmax/R_k)",14}");
        bool proportional = true;
        double ratioRef = 0;
        for (int k = 0; k < K; k++)
        {
            double m = 0;
            for (int j = k; j < K; j++) m += A[j];
            double Rk = r0 * Math.Pow(LAMBDA, k);
            double lnr = Math.Log(Rmax / Rk);
            double ratio = m / lnr;
            if (k == 0) ratioRef = ratio;
            if (Math.Abs(ratio - ratioRef) > 1e-9) proportional = false;
            sb.AppendLine($"{k,7} {m,12:F6} {lnr,14:F6}");
        }

        sb.AppendLine();
        sb.AppendLine($"cumulative deficit m_k ∝ ln(Rmax/R_k) (log deficit): {proportional}");
        sb.AppendLine();
        sb.AppendLine("CLASSIFICATION: DERIVED — ρ profiles are GENERATED, not assumed.");
        sb.AppendLine("  • Native evolution equation identified: ∂_t A_k = D·Δ_k A_k (scale-space diffusion),");
        sb.AppendLine("    equivalently dα/dt = μ·∂H/∂α (entropy gradient flow).");
        sb.AppendLine("  • Its unique stable attractor is the uniform fixed point A_k = const = α=0, whose cumulative");
        sb.AppendLine("    deficit is the log-deficit ρ = ρ̄ − m ∝ ln(Rmax/r) — the flat-rotation-curve profile.");
        sb.AppendLine("  • Remaining input: the entropy-maximization (least-bias) principle itself is assumed; the");
        sb.AppendLine("    microscopic actualization mechanism that enforces it is still open.");
        Output.WriteLine(sb.ToString());

        Assert.True(proportional, "the uniform fixed point should equal the log-deficit profile");
    }
}
