namespace AT.Core.Research;

/// <summary>
/// Evaluates physical mechanisms for operator family transitions.
/// AT-X022: Operator Evolution Mechanism
/// </summary>
public static class OperatorMutationModel
{
    public static List<OperatorTransitionMetrics.TransitionMechanism> EvaluateMechanisms()
    {
        return new List<OperatorTransitionMetrics.TransitionMechanism>
        {
            new(
                "Density-Dependent Nonlinearity",
                "Graph Laplacian", "NLS Operator",
                true, true, true,
                "α = α(population): more species → higher field amplitude → larger α. "
                + "Bounded: max α limited by physical constraints. "
                + "Connects exactly 2 families (linear ↔ NLS)."
            ),

            new(
                "Environmental Coupling Modulation",
                "Graph Laplacian", "Any (external)",
                false, false, false,
                "Requires external agent to change coupling strengths. "
                + "Not internal to the species ecology."
            ),

            new(
                "Topology-Induced Gap Closure",
                "Graph Laplacian", "Graph Laplacian (different topology)",
                true, true, false,
                "Ring → Chain via edge removal. Same operator FAMILY — "
                + "both are graph Laplacians. No new carrier CLASS."
            ),

            new(
                "Magnetic Flux Penetration",
                "Graph Laplacian", "Magnetic Laplacian",
                false, false, true,
                "Requires external magnetic field. Not generated by species. "
                + "Would create Landau levels — genuinely new carrier class."
            ),

            new(
                "Three-Body Interaction Onset",
                "Graph Laplacian", "Hypergraph Laplacian",
                false, false, true,
                "Requires 3-body coupling terms. Not naturally emergent "
                + "from pairwise interactions. External modification needed."
            ),

            new(
                "State-Dependent Adaptation",
                "NLS Operator", "Adaptive Operator",
                true, true, true,
                "L(ψ) = L_Q + β·F(ψ). If β evolves with species, "
                + "operator continuously adapts. Potentially unbounded. "
                + "Requires feedback: species → β → operator → species."
            ),

            new(
                "Meta-Operator Dynamics",
                "Any", "Novel Emergent",
                false, false, true,
                "Operators that act on operators. Theoretical only. "
                + "No known physical realization. Would require a 'space of operators.'"
            ),
        };
    }
}
