<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FITS.Lib" Version="5.0.381" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.0" />
  </ItemGroup>

</Project>
