using System.Globalization;
using System.Text;
using AT.Core.ResearchXH;
using AT.Tests.Shared;

namespace AT.Tests.ResearchXH;

/// <summary>
/// AT-QG Phase 155 — Origin of the Z2 doublet symmetry. QG153 established the weak-isospin doublets arise
/// from exact Z2 spectral pairing (reflection + half-shift automorphisms). This phase asks WHY the
/// observable sector possesses the Z2 symmetry.
///
/// Tests: ATQG1550 (reflection + half-shift origin), ATQG1551 (attractor dynamics emergence + octave
/// bands), ATQG1552 (symmetry selection + classification).
/// </summary>
public class ATQG_Phase155_Z2SymmetryOriginTests : ResearchTestBase
{
    public ATQG_Phase155_Z2SymmetryOriginTests(ITestOutputHelper o) : base(o) { }

    [Fact]
    public void ATQG1550_ReflectionAndHalfShiftOrigin()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("ATQG1550: origin of the reflection and half-shift symmetries");

        sb.AppendLine("REFLECTION SYMMETRY (i → n−1−i):");
        sb.AppendLine($"  seed pattern reflection-invariant: {Z2SymmetryOrigin.SeedReflectionSymmetry()}");
        sb.AppendLine($"  final adjacency reflection-invariant: {Z2SymmetryOrigin.AdjacencyReflectionSymmetry()}");
        sb.AppendLine($"  reflection ORIGINATES in the dynamics: {Z2SymmetryOrigin.ReflectionFromDynamics()}");
        sb.AppendLine();
        sb.AppendLine("HALF-SHIFT SYMMETRY (i → i+n/2):");
        sb.AppendLine($"  seed half-shift-invariant: {Z2SymmetryOrigin.SeedHalfShiftSymmetry()}");
        sb.AppendLine($"  final adjacency half-shift-invariant: {Z2SymmetryOrigin.AdjacencyHalfShiftSymmetry()}");
        sb.AppendLine($"  half-shift ORIGINATES in the period-3 seed: {Z2SymmetryOrigin.HalfShiftFromSeed()}");
        sb.AppendLine();
        sb.AppendLine("CONCLUSION: the reflection symmetry is GENERATED by the attractor dynamics (the seed");
        sb.AppendLine("is not reflection-invariant), while the half-shift symmetry inherits the period-3 seed");
        sb.AppendLine("structure (n/2 = 48, 48 mod 3 = 0).");
        Output.WriteLine(sb.ToString());

        Assert.True(Z2SymmetryOrigin.ReflectionFromDynamics(), "reflection should originate in the dynamics");
        Assert.True(Z2SymmetryOrigin.HalfShiftFromSeed(), "half-shift should originate in the period-3 seed");
    }

    [Fact]
    public void ATQG1551_AttractorDynamicsAndOctaveBands()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("ATQG1551: attractor dynamics emergence and octave-band structure");

        sb.AppendLine("SYMMETRY EMERGENCE DURING ATTRACTOR EVOLUTION:");
        foreach (var (s, r, h, reg, d) in Z2SymmetryOrigin.SymmetryEmergence())
            sb.AppendLine($"  steps={s}: reflection={r}, halfShift={h}, regular={reg} (degree {d})");
        sb.AppendLine($"  attractor converges to a fully symmetric 12-regular state: {Z2SymmetryOrigin.AttractorConvergesSymmetric()}");
        sb.AppendLine();
        sb.AppendLine("OCTAVE-BAND STRUCTURE:");
        foreach (var (b, m, d) in Z2SymmetryOrigin.OctaveBands())
            sb.AppendLine($"  band {b}: {m} modes, local Weyl δ={d:F3}");
        sb.AppendLine($"  family count: {Z2SymmetryOrigin.FamilyCount()}");
        sb.AppendLine();
        sb.AppendLine("CONCLUSION: the symmetries EMERGE as the dynamics saturate the attractor (both present");
        sb.AppendLine("by step 5, stable to step 200) and the resulting spectrum carries the 3-family octave");
        sb.AppendLine("band structure.");
        Output.WriteLine(sb.ToString());

        Assert.True(Z2SymmetryOrigin.AttractorConvergesSymmetric(), "attractor should converge to the symmetric state");
        Assert.True(Z2SymmetryOrigin.ThreeFamilies(), "the 3-family octave structure should be present");
        var em = Z2SymmetryOrigin.SymmetryEmergence();
        Assert.True(em[0].HalfShift && !em[0].Reflection, "half-shift should be present early, reflection emerges later");
    }

    [Fact]
    public void ATQG1552_SymmetrySelectionAndClassification()
    {
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        PrintHeader("ATQG1552: symmetry-selection mechanism and classification");

        sb.AppendLine("SYMMETRY-SELECTION MECHANISM (circulant ring):");
        sb.AppendLine($"  adjacency is CIRCULANT (rotationally symmetric ring): {Z2SymmetryOrigin.IsCirculant()}");
        sb.AppendLine($"  connection radius k = {Z2SymmetryOrigin.ConnectionRadius()} → degree {2 * Z2SymmetryOrigin.ConnectionRadius()}");
        sb.AppendLine($"  invariant rotation shifts: {Z2SymmetryOrigin.RotationSymmetryCount()}/11");
        sb.AppendLine($"  symmetry-selection mechanism (circulant + both Z2 symmetries): {Z2SymmetryOrigin.SymmetrySelectionMechanism()}");
        sb.AppendLine();
        sb.AppendLine("  The dynamics create links to CYCLIC neighbors (i+d) mod n, generating the circulant");
        sb.AppendLine("  ring C_n(1..k) with dihedral automorphism group D_n (rotation Z_n + reflection). The");
        sb.AppendLine("  2D irreducible representations of D_n generate the Z2 doublets.");
        sb.AppendLine();
        int score = Z2SymmetryOrigin.OriginScore();
        string cls = Z2SymmetryOrigin.Classify();
        sb.AppendLine($"z2-symmetry-origin score (0..5): {score}");
        sb.AppendLine($"  +1 reflection from dynamics: {Z2SymmetryOrigin.ReflectionFromDynamics()}");
        sb.AppendLine($"  +1 half-shift from seed: {Z2SymmetryOrigin.HalfShiftFromSeed()}");
        sb.AppendLine($"  +1 attractor converges symmetric: {Z2SymmetryOrigin.AttractorConvergesSymmetric()}");
        sb.AppendLine($"  +1 3-family octave structure: {Z2SymmetryOrigin.ThreeFamilies()}");
        sb.AppendLine($"  +1 symmetry-selection mechanism: {Z2SymmetryOrigin.SymmetrySelectionMechanism()}");
        sb.AppendLine();
        sb.AppendLine($"CLASSIFICATION: {cls}");
        sb.AppendLine();
        sb.AppendLine("  • ACCIDENTAL rejected: the symmetries are structurally generated (circulant dynamics,");
        sb.AppendLine("    period-3 seed) and stable across evolution.");
        sb.AppendLine("  • DYNAMICAL rejected: the mechanism is stronger than mere emergence — a structural");
        sb.AppendLine("    selection exists (the circulant ring → dihedral group D_n).");
        sb.AppendLine("  • SYMMETRY ORIGIN accepted: the Z2 doublet symmetry is a genuine, dynamically-selected");
        sb.AppendLine("    property — the attractor generates a circulant ring C_n(1..6) with dihedral symmetry");
        sb.AppendLine("    D_n (rotation Z_n + reflection); reflection arises from the dynamics, half-shift from");
        sb.AppendLine("    the period-3 seed, and the 2D irreps of D_n generate the Z2 doublets — the symmetry");
        sb.AppendLine("    origin of the weak-isospin doublet structure.");
        Output.WriteLine(sb.ToString());

        Assert.True(Z2SymmetryOrigin.IsCirculant(), "the adjacency should be a circulant ring");
        Assert.True(score >= 4, "symmetry-origin score should be strong");
        Assert.Equal("SYMMETRY ORIGIN", cls);
    }
}
