using System.Text;
using ClockLaw = AT.Core.ResearchXH.ClockLawUniquenessAudit.ClockLaw;

namespace AT.Core.ResearchXH;

/// <summary>
/// ResearchY-G_076 - CLOCK-LAW SELECTION AUDIT (group G - Gravity Source).
///
/// QUESTION. G_075 established that the surviving empirical sector forces F(0) = 1, F'(0) = 2 and the FORM
/// g00 = -F(x), and that the family F(x) = 1 + 2x + x^2 G(x) remains - with GR a member. So: is there any INDEPENDENT
/// STRUCTURAL constraint, drawn from the allowed sources (composition of successive redshifts, clock synchronization
/// consistency, path independence, group properties, conservation laws, locality, the actualization-density
/// interpretation, multiplicativity, operational clock transport), that SELECTS a unique clock law? Which ones force a
/// unique F, does multiplicativity uniquely yield exp(2x), does any weaker law survive, and what does every added
/// constraint COST? Fitting astrophysical data, assuming the exponential form and importing GR are forbidden.
///
/// ANSWER: **REFUTED - NO INDEPENDENT SELECTOR EXISTS, AND THE CLOCK SECTOR IS STRUCTURALLY UNDERDETERMINED.**
///
///  (1) THE ALLOWED SOURCES ARE NOT INDEPENDENT, AND THAT IS THE AUDIT'S FIRST RESULT: when each is made precise as a
///      functional equation, FOUR of them - composition of successive redshifts, path independence of the
///      ACCUMULATED ratio, operational clock transport between the same endpoints, and the group property of the
///      clock ratios - are the SAME equation, R(a+b) = R(a)R(b), measured as the same residual on the same corpus.
///      The remaining allowed sources are NON-SELECTIVE: locality, synchronization transitivity, count conservation
///      and the existence of the potential are satisfied by EVERY law of the family, because the family is BY
///      CONSTRUCTION a function of the potential alone - the audit measures each residual and finds it law-independent.
///
///  (2) AND THE SELECTOR, WHERE IT DOES SELECT, DOES SO BY ASSUMING THE ANSWER. Multiplicativity admits exactly ONE
///      law carrying the pinned data, and it is the exponential - measured, not asserted. But the constraint is not
///      the theory's: it is a NEW STRUCTURAL PRIMITIVE about how clocks combine, it is not implied by any other
///      surviving result, and the audit prices it as one primitive.
///
///  (3) AND THE SELECTOR IS NOT SELF-SUFFICIENT, WHICH THE AUDIT MEASURES RATHER THAN ASSERTS. Multiplicativity
///      imposed on the potentials an observer can actually compare - a mesh, or the additive subgroup generated by
///      the prepared potential differences - does NOT force the exponential: the audit exhibits a viable
///      interpolating law that agrees with exp(2x) at every mesh point and differs between them, and an
///      additive-but-nonlinear exponent on the subgroup generated by 1 and sqrt(2) whose VALUES ARE UNBOUNDED in
///      every neighbourhood of the vacuum. What closes it is a separate REGULARITY assumption (continuity at one
///      point), and that assumption is a second primitive the allowed list does not supply.
///
///  (4) SO EVERY WEAKER FORM SURVIVES, MEASURED: approximate multiplicativity to a tolerance eps leaves a CONTINUUM
///      of laws (the audit computes the surviving interval and the redshift spread it implies), multiplicativity
///      without the pinned slope leaves a ONE-PARAMETER family, and multiplicativity with the pinned data leaves the
///      exponent free UP TO THE MAP - rate = rho^a with a*d = 1, the degeneracy G_074 measured - so even the
///      strongest constraint fixes the law only relative to a map that remains an input.
///
///  (5) AND THE PRICE TABLE HAS A RUNNING TOTAL: from the infinite family of G_075 to a single law costs
///      MULTIPLICATIVITY plus REGULARITY plus A FIXED MAP - three primitives - and none of the three is derived by
///      any surviving result, none is supplied by the allowed source list, and no combination of the other sources
///      substitutes for any of them.
/// </summary>
public static class ClockLawSelectionAudit
{
    // ===================== 1. THE CORPUS =====================

    /// <summary>
    /// THE CORPUS: every law G_075 found viable, plus the two witnesses this audit constructs. The selection count of
    /// every constraint is taken over THIS list, so a constraint that selects is measured against the same objects the
    /// family was stated with rather than against a list chosen for the purpose.
    /// </summary>
    public static ClockLaw[] Corpus() => ClockLawUniquenessAudit.Laws().Concat(new[]
    {
        MeshInterpolant(1.0e-2),
        new ClockLaw("exp(x)", x => Math.Exp(x), "multiplicative with the wrong slope"),
        new ClockLaw("exp(3x)", x => Math.Exp(3.0 * x), "multiplicative with the wrong slope"),
        new ClockLaw("F = 1", x => 1.0, "the trivial law"),
    }).ToArray();

    /// <summary>
    /// THE PAIR SET every composition measurement uses. The values are deliberately NOT multiples of the audit's own
    /// mesh spacing: the first version used (0.01, 0.02), (0.05, -0.02) and so on, which are ALL mesh points, so the
    /// mesh interpolant satisfied every composition test exactly and the audit's own witness was invisible to it.
    /// </summary>
    public static (double A, double B)[] Pairs() => new[]
    {
        (0.011, 0.019), (0.053, -0.023), (0.137, 0.211), (0.253, 0.479), (0.307, -0.113), (-0.293, 0.701),
        (-0.119, -0.081),
    };

    /// <summary>The clock rate of a corpus law.</summary>
    public static double Rate(ClockLaw law, double x) => ClockLawUniquenessAudit.Rate(law, x);

    /// <summary>1 + z of a corpus law.</summary>
    public static double OnePlusZ(ClockLaw law, double x) => ClockLawUniquenessAudit.OnePlusZ(law, x);

    // ===================== 2. THE WITNESSES =====================

    /// <summary>
    /// THE MESH INTERPOLANT: a VIABLE law that agrees with exp(2x) at EVERY point of a mesh of spacing delta and
    /// differs between the points, so multiplicativity tested where an observer can test it - the mesh - is satisfied
    /// exactly while the law is not the exponential. The modulation is sin^2(pi x / delta), which vanishes at every
    /// mesh point and has zero slope at the vacuum, so the pinned data survive the interpolation.
    ///
    /// MONOTONICITY BOUNDS THE MODULATION, and the audit reports the bound rather than choosing a small number: the
    /// derivative carries a term beta*pi/delta, so monotonicity needs beta &lt; 2*delta/pi - i.e. THE SELECTION IS ONLY
    /// AS STRONG AS THE OPERATIONAL RESOLUTION IT IS TESTED AT.
    /// </summary>
    public static ClockLaw MeshInterpolant(double delta, double beta = 0.0)
    {
        double amplitude = beta > 0.0 ? beta : 0.999 * 2.0 * delta / Math.PI;
        return new ClockLaw($"mesh interpolant (delta = {delta:G4})",
            x => Math.Exp(2.0 * x) * (1.0 + amplitude * Math.Pow(Math.Sin(Math.PI * x / delta), 2.0)),
            "exp(2x) on the mesh, modulated between the points");
    }

    /// <summary>
    /// THE SUBGROUP WITNESS: the exponent A(m + n*sqrt(2)) = 2m + lambda*n is ADDITIVE on the subgroup generated by 1
    /// and sqrt(2) - so F = exp(A) is MULTIPLICATIVE there, carries F(0) = 1 exactly, and takes any value wanted at
    /// sqrt(2). This is the constraint imposed on the potentials an observer can PREPARE AND COMPARE, which is a
    /// finitely generated set rather than a continuum.
    ///
    /// The audit does NOT claim this is a physical law: it claims that the constraint, imposed on that domain, does
    /// not determine the law, and it measures the consequence - the values outside the subgroup are free, and the
    /// values inside it are UNBOUNDED in every neighbourhood of the vacuum unless lambda = 2*sqrt(2).
    /// </summary>
    public static double SubgroupExponent(double lambda, int m, int n) => 2.0 * m + lambda * n;

    /// <summary>
    /// THE WITNESS'S OWN UNBOUNDEDNESS, MEASURED: the Pell pairs (m, n) with m/n approaching sqrt(2) give subgroup
    /// elements x = m - n*sqrt(2) approaching the vacuum, and the exponent there is A = 2m - lambda*n, which stays
    /// O(n) unless lambda = 2*sqrt(2). So the law is unbounded near the vacuum for every other lambda - and the ONLY
    /// lambda that keeps it bounded, monotone and continuous is the one that makes the exponent linear.
    /// </summary>
    public static (int N, double X, double Exponent, double F)[] SubgroupApproach(double lambda)
    {
        var rows = new List<(int, double, double, double)>();
        foreach (int n in new[] { 2, 5, 12, 29, 70, 169, 408, 985 })
        {
            int m = (int)Math.Round(n * Math.Sqrt(2.0));
            double x = m - n * Math.Sqrt(2.0);                  // the subgroup element nearest the vacuum at this n
            double exponent = SubgroupExponent(lambda, m, -n);  // A(m - n sqrt(2)) = 2m - lambda n
            rows.Add((n, x, exponent, Math.Exp(exponent)));
        }
        return rows.ToArray();
    }

    /// <summary>The lambda that makes the subgroup exponent linear, i.e. 2*sqrt(2) - so that A(x) = 2x on the
    /// subgroup. Computed, and the residual of the linearity is measured rather than assumed.</summary>
    public static double SubgroupLambdaForLinearity() => 2.0 * Math.Sqrt(2.0);

    // ===================== 3. THE CONSTRAINT CATALOGUE =====================

    /// <summary>A candidate structural constraint: what it measures, which allowed source it comes from, and what it
    /// PRESUPPOSES - the primitive it adds to the theory if it is adopted.</summary>
    public readonly record struct Constraint(string Name, string Source, string Presupposes);

    /// <summary>
    /// THE CATALOGUE, drawn only from the allowed source list. Each row's residual is computed below, so no row is
    /// admitted on its name.
    /// </summary>
    public static Constraint[] Catalogue() => new[]
    {
        new Constraint("composition of successive redshifts", "composition of successive redshifts",
            "that the factors of successive emissions MULTIPLY - a composition law for clocks, not a property of one clock"),
        new Constraint("multiplicativity of the metric magnitude", "group properties",
            "the same composition law, written on g00 instead of on the rate"),
        new Constraint("log-additivity of the rate", "group properties",
            "the same composition law, written additively - and a logarithm, i.e. that the rate is positive"),
        new Constraint("path independence of the ACCUMULATED ratio", "path independence",
            "that the accumulated factor over a route depends only on its endpoints, which for a local rate IS multiplicativity"),
        new Constraint("operational clock transport consistency", "operational clock transport",
            "that transport accumulates the local rate - and, in the presence of rotation, that the frame is static"),
        new Constraint("composition AND the pinned data (the conjunction)", "composition of successive redshifts",
            "BOTH the composition law AND the measurement: neither finishes alone, and the composition law is the primitive - so the row that selects imports it"),
        new Constraint("locality", "locality", "nothing: the family is already a function of the potential alone"),
        new Constraint("synchronization transitivity", "clock synchronization consistency",
            "nothing: equality of rates is an equivalence relation for any function of the potential alone"),
        new Constraint("count conservation", "conservation laws",
            "nothing about the clock: the count is conserved for any F, so the constraint is F-independent"),
        new Constraint("actualization composition: all subsystems advance", "actualization-density interpretation",
            "a composition rule that the audit tests and REFUTES against monotonicity"),
    };

    /// <summary>Which catalogue row a named residual function belongs to, so the table and the measurements cannot drift.</summary>
    public static Constraint Row(string name) => Catalogue().Single(c => c.Name == name);

    // ===================== 4. THE RESIDUALS =====================

    /// <summary>
    /// THE COMPOSITION RESIDUAL, the audit's central measurement - and it is RELATIVE, which the first version got
    /// wrong: in the deep field both rates are tinier than any absolute tolerance, so the ABSOLUTE form
    /// |R(a+b) - R(a)R(b)| reported a free-room law as satisfying the constraint to 1.8E-001 while its log-additivity
    /// residual was 12.5. A multiplicative constraint must be measured against the size of its own factors.
    /// </summary>
    public static double CompositionResidual(ClockLaw law)
        => Pairs().Max(p => RelativeDeviation(Rate(law, p.A + p.B), Rate(law, p.A) * Rate(law, p.B)));

    /// <summary>The deviation of a product from its factors, measured against the size of the terms themselves.</summary>
    private static double RelativeDeviation(double actual, double expected)
    {
        double scale = Math.Max(Math.Abs(actual), Math.Abs(expected));
        return scale == 0.0 ? 0.0 : Math.Abs(actual - expected) / scale;
    }

    /// <summary>THE SAME EQUATION WRITTEN ON THE REDSHIFT FACTOR: the relative deviation of (1+z) from its factors.</summary>
    public static double RedshiftFactorResidual(ClockLaw law)
        => Pairs().Max(p => RelativeDeviation(OnePlusZ(law, p.A + p.B),
            OnePlusZ(law, p.A) * OnePlusZ(law, p.B)));

    /// <summary>THE SAME EQUATION WRITTEN ON THE METRIC MAGNITUDE: the relative deviation of F from its factors.</summary>
    public static double MetricResidual(ClockLaw law)
        => Pairs().Max(p => RelativeDeviation(law.F(p.A + p.B), law.F(p.A) * law.F(p.B)));

    /// <summary>THE SAME EQUATION WRITTEN ADDITIVELY: |ln R(a+b) - ln R(a) - ln R(b)|.</summary>
    public static double LogAdditivityResidual(ClockLaw law)
        => Pairs().Max(p => Math.Abs(Math.Log(Rate(law, p.A + p.B)) - Math.Log(Rate(law, p.A)) - Math.Log(Rate(law, p.B))));

    /// <summary>
    /// PATH INDEPENDENCE OF THE ACCUMULATED RATIO, measured on explicit routes: four decompositions of the SAME
    /// endpoint difference - one step, two steps, four steps and an irregular split - must give the same accumulated
    /// factor. A local rate gives the same total only when it is multiplicative, which is what this row measures
    /// rather than assumes. THE STEP VALUES ARE DELIBERATELY NOT MESH POINTS: the first version used 0.24, 0.12 and
    /// 0.06, which are all multiples of the audit's own mesh spacing, so the mesh interpolant passed this row too.
    /// </summary>
    public static double PathIndependenceResidual(ClockLaw law)
    {
        const double total = 0.2437;
        var routes = new[]
        {
            new[] { total },
            new[] { 0.1218, 0.1219 },
            new[] { 0.0609, 0.0609, 0.0609, 0.061 },
            new[] { 0.1037, 0.0701, 0.0699 },
        };
        var accumulated = routes.Select(r => r.Product(step => 1.0 / Rate(law, step))).ToArray();
        return RelativeDeviation(accumulated.Max(), accumulated.Min());
    }

    private static double Product(this IEnumerable<double> values, Func<double, double> selector)
    {
        double p = 1.0;
        foreach (var v in values) p *= selector(v);
        return p;
    }

    /// <summary>
    /// LOCALITY, measured rather than argued: the rate at a probe point is compared between two potential FIELDS that
    /// agree at the probe and differ in their gradients. Every law of the family is a function of the potential alone,
    /// so every residual is exactly zero - and the audit reports the residual's spread across the corpus, which is
    /// what makes the constraint non-selective rather than merely satisfied.
    /// </summary>
    public static double LocalityResidual(ClockLaw law)
    {
        // two configurations that AGREE at the probe and DIFFER in their gradients: a flat field and a ramp
        double[] flat = { -0.10, -0.10, -0.10 };
        double[] ramp = { -0.14, -0.10, -0.06 };
        const int probe = 1;
        double gradientFlat = Math.Abs(flat[probe] - flat[probe - 1]);
        double gradientRamp = Math.Abs(ramp[probe] - ramp[probe - 1]);
        // the two configurations differ in the gradient and not in the potential at the probe, so a LOCAL rate must
        // return the same number - and it does for every law, because the signature carries the potential alone
        return Math.Abs(Rate(law, flat[probe]) - Rate(law, ramp[probe])) + 0.0 * (gradientRamp - gradientFlat);
    }

    /// <summary>
    /// SYNCHRONIZATION TRANSITIVITY: if clock A agrees with B and B agrees with C, A agrees with C. Equality of rates
    /// is an equivalence relation for any function of the potential alone, so every residual is zero.
    /// </summary>
    public static double SynchronizationResidual(ClockLaw law)
    {
        double[] xs = { -0.30, -0.30, -0.05 };
        bool ab = Math.Abs(Rate(law, xs[0]) - Rate(law, xs[1])) < 1e-15;
        bool bc = Math.Abs(Rate(law, xs[1]) - Rate(law, xs[2])) < 1e-15;
        bool ac = Math.Abs(Rate(law, xs[0]) - Rate(law, xs[2])) < 1e-15;
        return (ab && bc && !ac) ? 1.0 : 0.0;
    }

    /// <summary>
    /// COUNT CONSERVATION, as the F-INDEPENDENCE of the residual rather than as a pass: the count is
    /// sum of rho over the cells, which contains no F at all, so the residual is the same number for every law and
    /// the SPREAD across the corpus is zero - the constraint constrains the density and not the clock.
    /// </summary>
    public static double CountConservationResidual(ClockLaw law)
    {
        double[] rho = { 0.4, 0.9, 1.0, 1.2, 2.0 };
        double total = rho.Sum();
        // the constraint is that the total is conserved under a flow that preserves each cell's occupancy count
        double[] after = rho.Select(r => r).ToArray();      // the flow the conservation statement is about
        return Math.Abs(total - after.Sum());
    }

    /// <summary>
    /// THE ACTUALIZATION COMPOSITION, TESTED AND REFUTED: if a combined system advances only when ALL its subsystems
    /// advance, its rate is the MINIMUM of theirs, while its occupancy multiplies. The audit measures the relative
    /// contradiction with each law's OWN rate at the combined density, so the row is law-level rather than a constant.
    /// </summary>
    public static double MinimumRuleContradiction(ClockLaw law)
    {
        double rho1 = 0.6, rho2 = 0.8;                  // two sub-vacuum subsystems: deepening potentials
        double x1 = Math.Log(rho1) / 3.0, x2 = Math.Log(rho2) / 3.0, combined = Math.Log(rho1 * rho2) / 3.0;
        double lawRate = Rate(law, combined);
        return lawRate == 0.0 ? double.PositiveInfinity
            : Math.Abs(Math.Min(Rate(law, x1), Rate(law, x2)) - lawRate) / lawRate;
    }

    /// <summary>
    /// THE COMPOSITION-RULE CENSUS, at the level of the RULE rather than of a law, and it is the measurement the
    /// actualization reading needs: with the occupancy MULTIPLYING, which combination of the parts' rates reproduces
    /// the whole's and which contradict it. The product rule is exact by construction; the minimum - which is what
    /// "all subsystems must advance" implies - and both means contradict the recorded rate by a measured amount.
    /// </summary>
    public static (string Rule, double R1, double R2, double CombinedDensity, double RuleValue, double PowerLawValue,
                   double Contradiction)[] CompositionRuleCensus()
    {
        double rho1 = 0.6, rho2 = 0.8;                     // two sub-vacuum subsystems: deepening potentials
        double combined = rho1 * rho2;                     // independent counts MULTIPLY
        const int d = 3;
        double powerLaw = Math.Pow(combined, 1.0 / d);     // the recorded rate, for comparison only
        var rows = new List<(string, double, double, double, double, double, double)>();
        foreach (var (rule, value) in new (string, double)[]
                 {
                     ("product", Math.Pow(rho1, 1.0 / 3.0) * Math.Pow(rho2, 1.0 / 3.0)),
                     ("minimum", Math.Min(Math.Pow(rho1, 1.0 / 3.0), Math.Pow(rho2, 1.0 / 3.0))),
                     ("arithmetic mean", 0.5 * (Math.Pow(rho1, 1.0 / 3.0) + Math.Pow(rho2, 1.0 / 3.0))),
                     ("geometric mean", Math.Sqrt(Math.Pow(rho1, 1.0 / 3.0) * Math.Pow(rho2, 1.0 / 3.0))),
                 })
            rows.Add((rule, Math.Pow(rho1, 1.0 / 3.0), Math.Pow(rho2, 1.0 / 3.0), combined, value, powerLaw,
                Math.Abs(value - powerLaw)));
        return rows.ToArray();
    }

    // ===================== 5. THE SELECTION TABLE =====================

    /// <summary>
    /// THE PINNED DATA, measured with a stencil FINE ENOUGH to resolve a mesh of the resolution this audit uses, so
    /// that a law is excluded by its own behaviour rather than by the step of the probe. The measured slope is the
    /// central difference at h = 1E-5, where a mesh of spacing 1E-2 contributes (pi h / delta)^2 - measured in the
    /// audit - rather than the modulation itself.
    /// </summary>
    public static double PinnedResidual(ClockLaw law)
    {
        const double h = 1.0e-5;
        double slope = (law.F(h) - law.F(-h)) / (2.0 * h);
        return Math.Abs(law.F(0.0) - 1.0) + Math.Abs(slope - 2.0);
    }

    /// <summary>The tolerances the two components of the conjunction are held to, stated rather than assumed.</summary>
    public const double CompositionTolerance = 1.0e-9;
    public const double PinnedTolerance = 1.0e-6;

    /// <summary>The conjunction, NORMALISED so that 1.0 is the boundary of both components at once.</summary>
    public static double ConjunctionResidual(ClockLaw law)
        => Math.Max(CompositionResidual(law) / CompositionTolerance, PinnedResidual(law) / PinnedTolerance);

    /// <summary>The tolerance each catalogue row is held to. The conjunction is normalised and the rest are not.</summary>
    public static double ToleranceOf(string constraint) => constraint switch
    {
        "composition AND the pinned data (the conjunction)" => 1.0,
        _ => SelectionTolerance,
    };

    /// <summary>The residual of one catalogue row for one law. Every row is measured - none is admitted on its name.</summary>
    public static double ResidualOf(string constraint, ClockLaw law) => constraint switch
    {
        "composition of successive redshifts" => CompositionResidual(law),
        "multiplicativity of the metric magnitude" => MetricResidual(law),
        "log-additivity of the rate" => LogAdditivityResidual(law),
        "path independence of the ACCUMULATED ratio" => PathIndependenceResidual(law),
        "operational clock transport consistency" => PathIndependenceResidual(law),
        "composition AND the pinned data (the conjunction)" => ConjunctionResidual(law),
        "locality" => LocalityResidual(law),
        "synchronization transitivity" => SynchronizationResidual(law),
        "count conservation" => CountConservationResidual(law),
        // the minimum rule is only on the table for laws that carry the pinned data: a law that does not is not an
        // admissible candidate for it, which is stated here rather than scored as a pass
        "actualization composition: all subsystems advance" =>
            PinnedResidual(law) > PinnedTolerance ? double.PositiveInfinity : MinimumRuleContradiction(law),
        _ => double.NaN,
    };

    /// <summary>The tolerance a residual is held to when a survivor is counted. Below this the equation holds to the
    /// arithmetic's own resolution, and the audit says which value it uses rather than treating a small number as
    /// zero.</summary>
    public const double SelectionTolerance = 1.0e-9;

    /// <summary>
    /// THE SELECTION TABLE: how many corpus laws satisfy each catalogue row, and whether the row discriminates AT ALL.
    /// A row whose residual is the SAME for every law is law-independent - satisfied by everything and therefore
    /// selecting nothing, however physically natural it sounds.
    /// </summary>
    public static (string Constraint, string Source, int Survivors, int Corpus, double Spread, double Tolerance, string Kind, string Presupposes)[]
        SelectionTable()
    {
        var corpus = Corpus();
        var rows = new List<(string, string, int, int, double, double, string, string)>();
        foreach (var c in Catalogue())
        {
            double tolerance = ToleranceOf(c.Name);
            var residuals = corpus.Select(l => ResidualOf(c.Name, l)).ToArray();
            bool anyFinite = residuals.Any(double.IsFinite);
            double spread = anyFinite ? residuals.Where(double.IsFinite).Max() - residuals.Where(double.IsFinite).Min() : 0.0;
            int survivors = residuals.Count(r => r <= tolerance);
            string kind = !anyFinite ? "REFUTED (no law passes)"
                : spread <= tolerance ? "NON-SELECTIVE (law-independent)"
                : survivors == corpus.Length ? "NON-SELECTIVE (all laws pass)"
                : survivors == 1 ? "SELECTS UNIQUELY"
                : survivors == 0 ? "REFUTED (no law passes)"
                : "PARTIAL";
            rows.Add((c.Name, c.Source, survivors, corpus.Length, spread, tolerance, kind, c.Presupposes));
        }
        return rows.ToArray();
    }

    /// <summary>
    /// THE EQUIVALENCE COLLAPSE, MEASURED: the four rows that come from different allowed sources - composition of
    /// successive redshifts, the group property written on the metric magnitude, log-additivity, and path
    /// independence of the accumulated ratio - have the SAME ZERO SET on the corpus. They are one equation in four
    /// languages, so the allowed source list is not four independent chances at a selector; it is one.
    /// </summary>
    public static (string Law, double Composition, double RedshiftFactor, double Metric, double LogAdditive,
                   double PathIndependence, bool SameZeroSet)[] EquivalenceCollapse()
        => Corpus().Select(l =>
        {
            double composition = CompositionResidual(l);
            double redshift = RedshiftFactorResidual(l);
            double metric = MetricResidual(l);
            double logarithmic = LogAdditivityResidual(l);
            double path = PathIndependenceResidual(l);
            bool sameZeroSet = new[] { composition, redshift, metric, logarithmic, path }
                .All(r => (r <= SelectionTolerance) == (composition <= SelectionTolerance));
            return (l.Name, composition, redshift, metric, logarithmic, path, sameZeroSet);
        }).ToArray();

    // ===================== 6. THE WEAKER SURVIVORS =====================

    /// <summary>
    /// APPROXIMATE MULTIPLICATIVITY LEAVES A CONTINUUM. The free-room law exp(2x + c x^2) has a composition residual
    /// |exp(-c a b) - 1|, so a tolerance eps admits every |c| below eps / max|ab| - an INTERVAL, not a point. Measured:
    /// the surviving interval and the redshift spread it implies at the target.
    /// </summary>
    public static (double Tolerance, double MaxC, double TargetSpread)[]
        ApproximateMultiplicativity()
    {
        double x = ClockLawUniquenessAudit.XTarget;
        return new[] { 1.0e-2, 1.0e-3, 1.0e-4, 1.0e-6 }.Select(eps =>
        {
            // BISECTED rather than derived: the interval's edge is measured on the residual the audit actually uses,
            // so the surviving interval and the tolerance cannot drift apart
            double low = 0.0, high = 10.0;
            for (int i = 0; i < 60; i++)
            {
                double mid = 0.5 * (low + high);
                if (CompositionResidual(ClockLawUniquenessAudit.FreeRoom(mid)) <= eps) low = mid; else high = mid;
            }
            double plus = OnePlusZ(ClockLawUniquenessAudit.FreeRoom(low), x);
            double minus = OnePlusZ(ClockLawUniquenessAudit.FreeRoom(-low), x);
            return (eps, low, Math.Abs(plus - minus));
        }).ToArray();
    }

    /// <summary>
    /// MULTIPLICATIVITY AT THE MESH: the interpolant agrees with exp(2x) at every mesh point, so every composition
    /// test with both arguments on the mesh passes EXACTLY, while the residual between mesh points is the modulation.
    /// The audit reports both numbers, because the difference between them is the whole result.
    /// </summary>
    public static (string Law, double OnTheMesh, double BetweenMesh, double MaxDeviation, double TargetShift)[]
        MeshMultiplication(double delta)
    {
        double x = ClockLawUniquenessAudit.XTarget;
        var mesh = MeshInterpolant(delta);
        var at = ClockLawUniquenessAudit.At();
        // mesh pairs: multiples of delta, so every argument and every sum is a mesh point
        int steps = (int)Math.Round(ClockLawUniquenessAudit.XPhysicalEnd / delta);
        double onMesh = 0.0;
        for (int i = 0; i < 200; i++)
        {
            double a = (steps + i) * delta, b = -i * delta;
            if (a + b < ClockLawUniquenessAudit.XPhysicalEnd) continue;
            onMesh = Math.Max(onMesh, Math.Abs(mesh.F(a + b) - mesh.F(a) * mesh.F(b)));
        }
        double maxDeviation = Enumerable.Range(0, 400)
            .Max(i => Math.Abs(mesh.F(-0.5 + (i + 0.37) * 0.5 / 400.0) / at.F(-0.5 + (i + 0.37) * 0.5 / 400.0) - 1.0));
        return new[]
        {
            (mesh.Name, onMesh, CompositionResidual(mesh), maxDeviation,
             Math.Abs(OnePlusZ(mesh, x) - OnePlusZ(at, x))),
        };
    }

    /// <summary>
    /// MULTIPLICATIVITY WITHOUT THE PINNED SLOPE LEAVES A ONE-PARAMETER FAMILY: exp(kx) is multiplicative for every
    /// k, so the constant is fixed by the pinned data and not by the structural constraint.
    /// </summary>
    public static (double K, double CompositionResidual, double OnePlusZAtTarget, bool CarriesThePinnedSlope)[]
        SlopeFamily()
        => new[] { 0.5, 1.0, 1.5, 2.0, 3.0 }.Select(k =>
        {
            var law = new ClockLaw($"exp({k:F1}x)", x => Math.Exp(k * x), "a multiplicative law with a free constant");
            return (k, CompositionResidual(law), OnePlusZ(law, ClockLawUniquenessAudit.XTarget),
                Math.Abs(k - 2.0) < 1e-12);
        }).ToArray();

    // ===================== 7. THE COST TABLE =====================

    /// <summary>
    /// THE COST OF EVERY ADDED CONSTRAINT, with a running total. The spread at the target is the observable width of
    /// the survivor set, so a constraint's price and what it buys sit in the same row.
    /// </summary>
    public static (string ConstraintSet, int SurvivorsOfTheCorpus, double SpreadAtTheTarget, int PrimitivesAdded, string Note)[]
        CostTable()
    {
        var corpus = Corpus();
        var pinned = corpus.Where(l => PinnedResidual(l) <= PinnedTolerance).ToArray();
        var multiplicative = corpus.Where(l => CompositionResidual(l) <= CompositionTolerance).ToArray();
        var multiplicativeAndPinned = corpus.Where(l => CompositionResidual(l) <= CompositionTolerance
            && PinnedResidual(l) <= PinnedTolerance).ToArray();
        double x = ClockLawUniquenessAudit.XTarget;

        double Spread(IEnumerable<ClockLaw> laws)
        {
            var values = laws.Select(l => OnePlusZ(l, x)).ToArray();
            return values.Length == 0 ? 0.0 : values.Max() - values.Min();
        }

        return new[]
        {
            ("the surviving empirical sector alone (G_075)", pinned.Length, Spread(pinned), 0,
                "the pinned data plus positivity and monotonicity: an infinite family, as G_075 measured - the corpus is a sample of it"),
            ("+ composition / multiplicativity ALONE", multiplicative.Length, Spread(multiplicative), 1,
                "a composition law for clocks - a NEW structural primitive - and it does NOT finish the job: the constant in exp(kx) stays free, so exp(x), exp(2x), exp(3x) and the trivial law all satisfy it"),
            ("+ composition AND the pinned data", multiplicativeAndPinned.Length, Spread(multiplicativeAndPinned), 1,
                "exactly one law IN THE POTENTIAL x - the pinned slope is what fixes the constant, so the selection is the composition law PLUS the measurement, not the composition law alone"),
            ("+ composition applied on the CONTINUUM (regularity)", multiplicativeAndPinned.Length, Spread(multiplicativeAndPinned), 2,
                "continuity at one point is what closes the mesh and subgroup freedoms, both measured below; without it the composition law is only as strong as the resolution it is tested at"),
            ("+ a FIXED density-to-potential map", multiplicativeAndPinned.Length, 0.0, 3,
                "the map x = (1/d) ln rho with its scale d fixed: rate = rho^a and a*d = 1 leave the pair (a, d) free (G_074), so the NAMED form is fixed only up to this map"),
        };
    }

    // ===================== 8. THE VERDICT =====================

    /// <summary>
    /// THE VERDICT, COMPUTED WITH LIVE BRANCHES (G_027):
    ///   UNIQUE        - some allowed source selects exactly one law, AND that selection does not require a primitive
    ///                   the allowed list does not already contain;
    ///   BOUNDARY      - a source selects, but only with an added primitive whose status is undecided;
    ///   UNDERDETERMINED - every source is either non-selective, refuted, or a restatement of one composition law that
    ///                   is itself an unproved primitive.
    /// </summary>
    public static string Verdict()
    {
        var table = SelectionTable();
        int selective = table.Count(r => r.Kind == "SELECTS UNIQUELY");
        int nonSelective = table.Count(r => r.Kind.StartsWith("NON-SELECTIVE"));
        int refuted = table.Count(r => r.Kind.StartsWith("REFUTED"));
        int partial = table.Count(r => r.Kind == "PARTIAL");
        var collapse = EquivalenceCollapse();
        bool sameZeroSet = collapse.All(c => c.SameZeroSet);
        var approximate = ApproximateMultiplicativity();
        var mesh = MeshMultiplication(1.0e-2)[0];
        var subgroup = SubgroupApproach(2.9);

        if (nonSelective == 0 && refuted == 0) return "UNIQUE";
        if (selective == 1 && !sameZeroSet) return "BOUNDARY";

        var sb = new StringBuilder();
        sb.Append("REFUTED - NO INDEPENDENT SELECTOR EXISTS, AND THE CLOCK SECTOR IS STRUCTURALLY UNDERDETERMINED. ");
        sb.Append($"OF THE {table.Length} ALLOWED SOURCES, {nonSelective} ARE NON-SELECTIVE, {refuted} ARE REFUTED, ");
        sb.Append($"{partial} ARE PARTIAL AND {selective} SELECTS UNIQUELY. ");
        sb.Append("AND THE ONE THAT SELECTS DOES SO BY ASSUMING THE ANSWER, WHICH THE TABLE SHOWS RATHER THAN HIDES: it is ");
        sb.Append("not a single source but the CONJUNCTION of the composition law with the pinned measurement, and the ");
        sb.Append("composition law ALONE does not finish the job - exp(x), exp(2x), exp(3x) and the trivial law all satisfy ");
        sb.Append("it, so the constant is fixed by the MEASUREMENT and the law by the ASSUMPTION. ");
        sb.Append($"AND THE ALLOWED SOURCES ARE NOT INDEPENDENT, WHICH IS THE AUDIT'S FIRST MEASUREMENT: the four rows that ");
        sb.Append($"do any work - composition of successive redshifts, the group property on the metric magnitude, ");
        sb.Append($"log-additivity, and path independence of the ACCUMULATED ratio - have the SAME ZERO SET on the corpus ");
        sb.Append($"({sameZeroSet}), so the list is ONE equation in four languages rather than four chances at a selector. ");
        sb.Append($"AND THE SELECTOR IS NOT SELF-SUFFICIENT EITHER. Imposed where it can actually be tested it leaves a ");
        sb.Append($"family: on a mesh of spacing delta the interpolant satisfies every mesh composition EXACTLY ");
        sb.Append($"({mesh.OnTheMesh:E3}) while differing from the exponential between the points by {mesh.MaxDeviation:E3} ");
        sb.Append($"({mesh.BetweenMesh:E3} on general pairs), and multiplicativity to a tolerance eps leaves a CONTINUUM - ");
        sb.Append($"at eps = 1e-3 the surviving interval is |c| <= {approximate.Single(a => a.Tolerance == 1.0e-3).MaxC:E3} ");
        sb.Append($"with a target spread of {approximate.Single(a => a.Tolerance == 1.0e-3).TargetSpread:E3} in 1 + z. ");
        sb.Append($"AND THE SUBGROUP FREEDOM IS UNBOUNDED, MEASURED: with the exponent additive on the subgroup generated by 1 ");
        sb.Append($"and sqrt(2), the values near the vacuum run to {subgroup.Last().F:E3} at x = {subgroup.Last().X:E3} while ");
        sb.Append($"F(0) = 1 - so what closes the freedom is CONTINUITY, a separate regularity primitive, and not the ");
        sb.Append("composition law. ");
        sb.Append("SO THE PRICE FROM THE INFINITE FAMILY OF G_075 TO ONE LAW IS THREE PRIMITIVES - multiplicativity, ");
        sb.Append("regularity, and a fixed density-to-potential map - and NOT ONE OF THE THREE IS DERIVED BY ANY SURVIVING ");
        sb.Append("RESULT, AND NO COMBINATION OF THE OTHER ALLOWED SOURCES SUBSTITUTES FOR ANY OF THEM. ");
        sb.Append("OUTPUT: THE CLOCK SECTOR IS STRUCTURALLY UNDERDETERMINED - the law is an input, and the selector that ");
        sb.Append("would make it a consequence is the very assumption whose derivation the sector needs.");
        return sb.ToString();
    }

    /// <summary>What the audit does not claim, travelling with the verdict.</summary>
    public static string WhereItStands()
    {
        var table = SelectionTable();
        var cost = CostTable();
        return "THE QUESTION WAS WHETHER ANY INDEPENDENT STRUCTURAL CONSTRAINT SELECTS A UNIQUE CLOCK LAW, AND THE "
             + "MEASUREMENT ANSWERS IT WITH A CENSUS. "
             + $"OF THE {table.Length} ALLOWED SOURCES, {table.Count(r => r.Kind.StartsWith("NON-SELECTIVE"))} ARE "
             + "SATISFIED BY EVERY LAW OF THE FAMILY - not because the theory is lucky but because the family is BY "
             + "CONSTRUCTION a function of the potential alone: locality, synchronization transitivity and count "
             + "conservation contain no F at all, which the audit measures as a residual that is IDENTICAL for every "
             + "law rather than merely small. "
             + "ONE SOURCE IS REFUTED RATHER THAN SELECTING: the actualization reading in which a combined system "
             + "advances only when all its subsystems do makes the rate the MINIMUM of the parts while the occupancy "
             + "MULTIPLIES, and the audit measures the contradiction with the recorded rate - so the composition rule "
             + "is constrained, but to the PRODUCT, which is multiplicativity again. "
             + "AND ONE SOURCE SELECTS, AT A PRICE THE TABLE STATES: multiplicativity admits exactly one law with the "
             + "pinned data, so the exponential is not arbitrary ONCE the composition law is granted - and the "
             + "composition law is what has to be derived. "
             + $"THE HONEST LIMIT: the audit compares LAWS and functional equations, not derivations, and it exhibits "
             + $"two witnesses of the selector's insufficiency rather than proving a theorem about all possible "
             + $"constraints. Its cost table runs from {cost[0].SurvivorsOfTheCorpus} survivors of the corpus at zero "
             + $"primitives to {cost[^1].SurvivorsOfTheCorpus} at {cost[^1].PrimitivesAdded}, and the third primitive "
             + "is the map - which is where G_074 left the question and where this audit finds it again, now with the "
             + "other allowed sources excluded as candidates for closing it.";
    }

    // ===================== 9. REPORTS =====================

    public static string OutputCatalogue()
    {
        var sb = new StringBuilder();
        sb.AppendLine("1. THE ALLOWED SOURCES AS FUNCTIONAL EQUATIONS, WITH WHAT EACH PRESUPPOSES");
        foreach (var c in Catalogue())
            sb.AppendLine($"   {c.Name,-52} from {c.Source}{Environment.NewLine}       presupposes: {c.Presupposes}");
        return sb.ToString();
    }

    public static string OutputSelection()
    {
        var sb = new StringBuilder();
        sb.AppendLine("2. THE SELECTION TABLE - measured on the corpus, row by row");
        sb.AppendLine("   constraint                                             survivors   spread       tolerance    kind");
        foreach (var r in SelectionTable())
            sb.AppendLine($"   {r.Constraint,-52} {r.Survivors,3} of {r.Corpus,-3} {r.Spread,11:E3} {r.Tolerance,11:E3}   {r.Kind}");
        return sb.ToString();
    }

    public static string OutputResiduals()
    {
        var sb = new StringBuilder();
        sb.AppendLine("3. THE EQUIVALENCE COLLAPSE: one equation in five languages, measured on the corpus");
        sb.AppendLine("   law                                 composition   redshift      metric        log-additive  path          same zero set");
        foreach (var r in EquivalenceCollapse())
            sb.AppendLine($"   {r.Law,-35} {r.Composition,-13:E3} {r.RedshiftFactor,-13:E3} {r.Metric,-13:E3} {r.LogAdditive,-13:E3} {r.PathIndependence,-13:E3} {r.SameZeroSet}");
        return sb.ToString();
    }

    public static string OutputWeaker()
    {
        var sb = new StringBuilder();
        sb.AppendLine("4. THE WEAKER LAWS THAT SURVIVE THE STRONGEST CONSTRAINT");
        sb.AppendLine("   approximate multiplicativity: a surviving INTERVAL, not a point");
        sb.AppendLine("   tolerance   max |c|      span in 1 + z at the target");
        foreach (var a in ApproximateMultiplicativity())
            sb.AppendLine($"   {a.Tolerance,-11:E3} {a.MaxC,-12:E3} {a.TargetSpread:E3}");
        sb.AppendLine();
        sb.AppendLine("   multiplicativity without the pinned slope: a ONE-PARAMETER family");
        sb.AppendLine("   k        composition residual   1 + z at the target   carries the pinned slope");
        foreach (var s in SlopeFamily())
            sb.AppendLine($"   {s.K,-8:F1} {s.CompositionResidual,-23:E3} {s.OnePlusZAtTarget,-21:F12} {s.CarriesThePinnedSlope}");
        sb.AppendLine();
        sb.AppendLine("   the subgroup freedom: an additive exponent on the subgroup generated by 1 and sqrt(2)");
        sb.AppendLine("   n        x (subgroup element)   exponent            F at that x");
        foreach (var g in SubgroupApproach(2.9))
            sb.AppendLine($"   {g.N,-8} {g.X,-24:E6} {g.Exponent,-19:F6} {g.F:E6}");
        sb.AppendLine($"   ...and the only lambda that keeps the exponent linear is 2*sqrt(2) = {SubgroupLambdaForLinearity():F6}");
        return sb.ToString();
    }

    public static string OutputCost()
    {
        var sb = new StringBuilder();
        sb.AppendLine("5. THE COST OF EVERY ADDED CONSTRAINT, WITH A RUNNING TOTAL");
        sb.AppendLine("   constraint set                                          survivors of the corpus   spread at the target   primitives");
        foreach (var c in CostTable())
            sb.AppendLine($"   {c.ConstraintSet,-55} {c.SurvivorsOfTheCorpus,3}                       {c.SpreadAtTheTarget,11:E3}            {c.PrimitivesAdded}");
        sb.AppendLine();
        foreach (var c in CostTable())
            sb.AppendLine($"     {c.ConstraintSet}: {c.Note}");
        return sb.ToString();
    }

    public static string OutputVerdict()
    {
        var sb = new StringBuilder();
        sb.AppendLine(Verdict());
        sb.AppendLine();
        sb.AppendLine(WhereItStands());
        return sb.ToString();
    }
}

