namespace AT.Core.ResearchXH;

/// <summary>
/// AT-QG Phase 1 — derive ρ from microscopic Q-event actualization dynamics. Models actualization as a
/// Galton–Watson branching process over logarithmic (octave) layers, where the per-octave deficit counts
/// A_k = A₀·μ^k are generated by branching ratio μ. The branching ratio maps to the abundance exponent via
/// μ = λ^(−α), so criticality (μ=1) ⟺ α=0 (the log-deficit attractor). Deterministic (expected values) only.
/// </summary>
public static class QEventBranching
{
    /// <summary>Per-octave deficit counts from a branching process with ratio μ: A_k = A₀·μ^k.</summary>
    public static double[] DeficitCounts(double A0, double mu, int K)
    {
        var a = new double[K];
        for (int k = 0; k < K; k++) a[k] = A0 * Math.Pow(mu, k);
        return a;
    }

    /// <summary>Cumulative deficit at octave k: m_k = Σ_{j≥k} A_j (the deficit enclosed inward of R_k).</summary>
    public static double CumulativeDeficit(double[] counts, int k)
    {
        double s = 0.0;
        for (int j = k; j < counts.Length; j++) s += counts[j];
        return s;
    }

    /// <summary>Abundance exponent from branching ratio: α = −ln μ / ln λ (so μ = λ^(−α)).</summary>
    public static double AlphaFromMu(double mu, double lambda) => -Math.Log(mu) / Math.Log(lambda);

    /// <summary>Branching ratio from abundance exponent: μ = λ^(−α).</summary>
    public static double MuFromAlpha(double alpha, double lambda) => Math.Pow(lambda, -alpha);

    /// <summary>
    /// Branching-generated deficit density m(r) = m₀·(r^(−α) − Rmax^(−α))/(r₀^(−α) − Rmax^(−α)) for α≠0,
    /// and the log-deficit m(r) = m₀·ln(Rmax/r)/ln(Rmax/r₀) at α=0 (μ=1). This is EXACTLY the cumulative sum of
    /// per-octave counts A_k = A₀·μ^k, normalized so m(r₀) = m₀.
    /// </summary>
    public static double DeficitDensity(double r, double m0, double alpha, double r0, double Rmax, double rhoBar = 1.0)
        => rhoBar - DeficitCollective.AbundanceDeficit(r, alpha, rhoBar, m0, r0, Rmax);

    /// <summary>Branching-generated density ρ(r) = ρ̄ − m(r).</summary>
    public static double Density(double r, double m0, double alpha, double r0, double Rmax, double rhoBar = 1.0)
        => rhoBar - DeficitDensity(r, m0, alpha, r0, Rmax, rhoBar);

    /// <summary>
    /// Intrinsic scale (in octaves) of a non-critical branching process: L = 1/|ln μ| (the e-folding length).
    /// Critical (μ=1) has L → ∞ (no preferred scale). This is the microscopic statement of scale-freeness.
    /// </summary>
    public static double BranchingScaleLength(double mu) => mu == 1.0 ? double.PositiveInfinity : 1.0 / Math.Abs(Math.Log(mu));

    // ── AT-QG Phase 7: critical branching (extinction vs runaway stability) ─────────

    /// <summary>
    /// Extinction probability for a Poisson(μ)-offspring Galton–Watson process: the smallest non-negative
    /// fixed point of q = e^(μ(q−1)). q = 1 for μ≤1 (certain extinction, but critical at μ=1); q &lt; 1 for μ&gt;1.
    /// </summary>
    public static double ExtinctionProbability(double mu, int iters = 2000)
    {
        if (mu <= 1.0) return 1.0;   // subcritical and critical: extinction is certain (q = 1 exactly)
        double q = 0.0;
        for (int i = 0; i < iters; i++) q = Math.Exp(mu * (q - 1.0));
        return q;
    }

    /// <summary>Total expected population over K generations: Σ μ^k (finite for μ&lt;1, linear at μ=1, exponential for μ&gt;1).</summary>
    public static double TotalExpectedPopulation(double mu, int K)
    {
        double s = 0.0;
        for (int k = 0; k < K; k++) s += Math.Pow(mu, k);
        return s;
    }
}
