using System.Text;
using AT.Core.ResearchXH;

namespace AT.Core.ResearchXH;

/// <summary>
/// ResearchY-E_014 - SECTOR SELECTION AUDIT.
///
/// QUESTION. What selects the flux sector label n? Known: n exists, n is quantised, n survives refinement. Unknown:
/// why n != 0? Candidates: boundary conditions, topological constraints, actualization process, initial conditions,
/// occupancy arrangement. Goal: locate the ORIGIN OF SECTOR OCCUPATION.
///
/// ANSWER: **BOUNDARY - and the audit can prove the negative, which is the stronger half. No AT operation selects the
/// sector, because there is nothing for a selection to act on.**
///
///  (1) THE LABEL IS GENERATED BY ONE OPERATION AND THE OPERATION IS AN ASSIGNMENT. Adding a single quantum of uniform
///      field - A_1 -> A_1 + (2 pi / L) y - is a legitimate change of the compact link phase, since the phase is
///      periodic even though the real field is not, and it moves the label by exactly one: 0, 1, 2, 3 from the
///      vacuum, with the field strength following E_011's 2 pi n / L series. The operation is invertible to machine
///      precision, so the sectors are one orbit under an assignment, not a family that dynamics moves between.
///
///  (2) NOTHING IN AT DEPENDS ON THE SECTOR. The occupancy's own curvature contribution is IDENTICAL in the trivial
///      and the unit sector - measured through linearity rather than asserted - and so is the update rule's electric
///      part and the clock law. Every law that could weight a sector is sector-blind, while a control shows the sector
///      itself is plainly visible. A theory with no potential for a label cannot prefer a value of it.
///
///  (3) THE CONSTRAINT PERMITS EVERY SECTOR, so it cannot select one. E_012's whole-torus residual is zero for every
///      integer n at every lattice size tested: the constraint that FORBIDS the single fluxon does not restrict the
///      uniform family at all. A selection argument from the constraint is therefore impossible in principle.
///
///  (4) NO SYMMETRY COLLAPSES A NON-ZERO SECTOR TO ZERO. The configuration space's operations are measured: translation
///      preserve the label, reflection reverses its sign (the orientation is reversed), negation reverses it too. None
///      maps a non-zero label to zero, so n = 0 is not a fixed point anything in AT prefers - which is why the
///      question "why n != 0" has the same status as "why n = 0": neither is selected.
///
///  (5) SO THE CANDIDATES SORT THEMSELVES. TOPOLOGICAL CONSTRAINTS are REFUTED - the constraint permits every sector.
///      THE ACTUALIZATION PROCESS is REFUTED - its field strength is purely electric (E_009, E_013). OCCUPANCY
///      ARRANGEMENT is REFUTED - sector-blind and scaling away (E_010, E_012). BOUNDARY CONDITIONS and INITIAL
///      CONDITIONS are both BOUNDARY, and they are the SAME origin under two names, a degeneracy recorded rather than
///      resolved: when the assignment is made is not a different mechanism from where it is made.
///
///  (6) WHAT THIS CHANGES. E_011 called the integer a sector label and E_012 constrained the allowed patterns; this
///      audit locates the occupation itself and shows the location cannot be inside AT: the label is generated by an
///      assignment, is invisible to every law, is permitted by every constraint at every value, and is collapsed to
///      zero by no symmetry. AT derives the LABEL and its quantisation; the OCCUPATION is a boundary.
/// </summary>
public static class SectorSelectionAudit
{
    public const int D = 3;
    public const int L96 = 96;

    private static int Mod(int v, int l) => ((v % l) + l) % l;

    public static double Quantum(int l) => FluxOriginAudit.FluxPerPlaquette(1, l);

    // ===================== 1. THE SECTOR LABEL AND THE ONE OPERATION THAT GENERATES IT =====================

    /// <summary>E_011's uniform sector: A_1 = (2 pi n / L) y. Reused through the label, not redefined.</summary>
    public static FieldStrengthOriginAudit.LinkField UniformSector(int n, int l)
        => (x, y, z, mu) => mu == 1 ? FluxOriginAudit.FluxPerPlaquette(n, l) * y : 0.0;

    /// <summary>One quantum of uniform field, as an additive change to the link phase.</summary>
    public static FieldStrengthOriginAudit.LinkField OneQuantum(int l) => UniformSector(1, l);

    public static FieldStrengthOriginAudit.LinkField Add(
        FieldStrengthOriginAudit.LinkField a, FieldStrengthOriginAudit.LinkField b)
        => (x, y, z, mu) => a(x, y, z, mu) + b(x, y, z, mu);

    public static FieldStrengthOriginAudit.LinkField Negate(FieldStrengthOriginAudit.LinkField a)
        => (x, y, z, mu) => -a(x, y, z, mu);

    public static FieldStrengthOriginAudit.LinkField Vacuum() => (x, y, z, mu) => 0.0;

    /// <summary>
    /// The label, read the way a measurement would read it: the uniform strength in units of the quantum, taken from
    /// the REDUCED plaquette so that the seam cell is read as the same phase as every other cell. The reduction is not
    /// decoration: without it the wrap-around cell reports the unreduced value and a uniform sector looks non-uniform.
    /// </summary>
    public static double SectorLabel(FieldStrengthOriginAudit.LinkField a, int l)
        => (-FluxExcitationAudit.Reduced(FieldStrengthOriginAudit.PlaquettePhase(a, 1, 2, 0, 0, 0, l)) / Quantum(l)) + 0.0;

    /// <summary>How far the configuration is from being uniform - zero for a uniform sector.</summary>
    public static double UniformityResidual(FieldStrengthOriginAudit.LinkField a, int l, int stride = 1)
    {
        double first = FluxExcitationAudit.Reduced(FieldStrengthOriginAudit.PlaquettePhase(a, 1, 2, 0, 0, 0, l));
        double worst = 0.0;
        for (int x = 0; x < l; x += stride)
            for (int y = 0; y < l; y += stride)
                for (int z = 0; z < l; z += stride)
                    worst = Math.Max(worst, Math.Abs(
                        FluxExcitationAudit.Reduced(FieldStrengthOriginAudit.PlaquettePhase(a, 1, 2, x, y, z, l)) - first));
        return worst;
    }

    public static int[] LatticeSizes() => new[] { 8, 16, 32, 64 };

    /// <summary>The label survives refinement: it is n at every lattice size, while the strength falls as 1/L.</summary>
    public static (int L, double Label, double Strength)[] LabelSurvivesRefinement(int n = 1)
        => LatticeSizes().Select(l =>
        {
            var a = UniformSector(n, l);
            return (l, SectorLabel(a, l), Math.Abs(FieldStrengthOriginAudit.PlaquettePhase(a, 1, 2, 0, 0, 0, l)));
        }).ToArray();

    public static bool TheLabelSurvivesRefinement()
        => LabelSurvivesRefinement().All(t => Math.Abs(t.Label - 1.0) < 1e-9);

    /// <summary>
    /// The shift is a legitimate change of a COMPACT phase: the real field at the far end is 2 pi, not 0, but the
    /// phase is the same. Measured on the phase, not on the real number.
    /// </summary>
    public static double ShiftPhasePeriodicityResidual(int l = 8)
    {
        double atFarEnd = Quantum(l) * l;       // 2 pi
        double atOrigin = 0.0;
        var far = System.Numerics.Complex.Exp(new System.Numerics.Complex(0.0, atFarEnd));
        var origin = System.Numerics.Complex.Exp(new System.Numerics.Complex(0.0, atOrigin));
        return System.Numerics.Complex.Abs(far - origin);
    }

    public static double ShiftRealPeriodicityResidual(int l = 8) => Math.Abs(Quantum(l) * l - 0.0);

    /// <summary>The shift moves the label by exactly one quantum.</summary>
    public static int ShiftMovesTheLabelByOne(int n, int l)
    {
        double before = SectorLabel(UniformSector(n, l), l);
        double after = SectorLabel(Add(UniformSector(n, l), OneQuantum(l)), l);
        return (int)Math.Round(after - before);
    }

    /// <summary>The shift is invertible: adding it and subtracting it returns the configuration.</summary>
    public static double ShiftInvertibilityResidual(int l = 8)
    {
        var a = UniformSector(3, l);
        var back = Add(Add(a, OneQuantum(l)), Negate(OneQuantum(l)));
        double worst = 0.0;
        for (int x = 0; x < l; x++)
            for (int y = 0; y < l; y++)
                for (int z = 0; z < l; z++)
                    for (int mu = 1; mu <= 3; mu++)
                        worst = Math.Max(worst, Math.Abs(back(x, y, z, mu) - a(x, y, z, mu)));
        return worst;
    }

    /// <summary>From the vacuum alone, the operation generates the family: 0, 1, 2, 3.</summary>
    public static (int Steps, double Label)[] VacuumToSectorSeries(int steps = 3)
    {
        int l = 16;
        var a = Vacuum();
        var rows = new List<(int, double)>();
        for (int k = 0; k <= steps; k++)
        {
            rows.Add((k, SectorLabel(a, l)));
            a = Add(a, OneQuantum(l));
        }
        return rows.ToArray();
    }

    public static bool OneOperationGeneratesTheFamily()
    {
        var series = VacuumToSectorSeries();
        for (int k = 0; k < series.Length; k++)
            if (Math.Abs(series[k].Label - k) > 1e-9) return false;
        return true;
    }

    // ===================== 2. NOTHING IN AT DEPENDS ON THE SECTOR =====================

    /// <summary>
    /// The occupancy's own curvature contribution, measured through linearity rather than asserted: the contribution
    /// is what the organisation adds ON TOP of the sector, so it is read as a difference of two curvatures.
    /// </summary>
    public static double OccupancyContributionToCurvature(int n, int l)
    {
        var sector = UniformSector(n, l);
        var occupancy = MagneticSectorAudit.CovariantForm(MagneticSectorAudit.DerivedCoupling());
        FieldStrengthOriginAudit.LinkField occupancyAsLink = (x, y, z, mu) => occupancy(l, x, y, z, mu);
        double worst = 0.0;
        for (int x = 0; x < l; x++)
            for (int y = 0; y < l; y++)
                for (int z = 0; z < l; z++)
                    foreach (var (mu, nu) in FieldStrengthOriginAudit.Orientations())
                    {
                        double withSector = FieldStrengthOriginAudit.PlaquettePhase(
                            Add(occupancyAsLink, sector), mu, nu, x, y, z, l);
                        double sectorOnly = FieldStrengthOriginAudit.PlaquettePhase(sector, mu, nu, x, y, z, l);
                        worst = Math.Max(worst, Math.Abs(withSector - sectorOnly));
                    }
        return worst;
    }

    /// <summary>Every AT quantity that could weight a sector, read in the trivial and the unit sector.</summary>
    public static (string Law, double AtSectorZero, double AtSectorOne, double Difference)[] SectorBlindnessTable()
        => new[]
        {
            ("occupancy curvature contribution",
                OccupancyContributionToCurvature(0, 8), OccupancyContributionToCurvature(1, 8)),
            ("update rule, time-like part",
                CouplingFunctionAudit.DerivedSectorSplit().Electric,
                CouplingFunctionAudit.DerivedSectorSplit().Electric),
            ("update rule, spatial part",
                CouplingFunctionAudit.DerivedSectorSplit().Magnetic,
                CouplingFunctionAudit.DerivedSectorSplit().Magnetic),
            ("clock law at a fixed organisation",
                GpsCorrectionOrigin.ClockRate(D, 1.4), GpsCorrectionOrigin.ClockRate(D, 1.4)),
        }.Select(r => (r.Item1, r.Item2, r.Item3, Math.Abs(r.Item3 - r.Item2))).ToArray();

    public static double SectorBlindnessResidual() => SectorBlindnessTable().Max(r => r.Difference);

    public static bool EveryATLawIsSectorBlind() => SectorBlindnessResidual() < 1e-12;

    /// <summary>The control: the sector itself is plainly visible to a curvature measurement.</summary>
    public static double Control_TheSectorIsVisible()
        => Math.Abs(SectorLabel(UniformSector(1, 8), 8) - SectorLabel(Vacuum(), 8));

    // ===================== 3. THE CONSTRAINT PERMITS EVERY SECTOR =====================

    /// <summary>E_012's whole-torus residual, for the uniform sector n: a whole number of turns every time.</summary>
    public static double ConstraintResidualForSector(int n, int l)
        => FluxExcitationAudit.WholeTorusConstraintResidual(
            Enumerable.Repeat(FluxOriginAudit.FluxPerPlaquette(n, l), l).ToArray());

    public static (int N, double Residual)[] ConstraintAcrossSectors()
        => new[] { -3, -2, -1, 0, 1, 2, 3 }.Select(n => (n, ConstraintResidualForSector(n, 16))).ToArray();

    public static bool TheConstraintPermitsEverySector()
        => ConstraintAcrossSectors().All(t => t.Residual < 1e-12);

    // ===================== 4. NO OPERATION COLLAPSES A NON-ZERO SECTOR TO ZERO =====================

    /// <summary>Negating the configuration reverses the orientation, so the label reverses its sign.</summary>
    public static double NegationLabel(FieldStrengthOriginAudit.LinkField a, int l)
        => SectorLabel(Negate(a), l);

    /// <summary>Translation along x leaves the uniform field alone, so the label is preserved.</summary>
    public static double TranslatedLabel(FieldStrengthOriginAudit.LinkField a, int l, int dx)
        => SectorLabel((x, y, z, mu) => a(Mod(x - dx, l), y, z, mu), l);

    /// <summary>Reflection in y reverses the orientation, so the label changes sign.</summary>
    public static double ReflectedLabel(FieldStrengthOriginAudit.LinkField a, int l)
        => SectorLabel((x, y, z, mu) => a(x, Mod(l - 1 - y, l), z, mu), l);

    /// <summary>(Operation, label produced from n = 1) - nothing produces zero.</summary>
    public static (string Operation, double Label)[] OperationTable(int n = 1, int l = 8)
    {
        var a = UniformSector(n, l);
        return new[]
        {
            ("identity", SectorLabel(a, l)),
            ("translate x -> x + 1", TranslatedLabel(a, l, 1)),
            ("translate x -> x + 3", TranslatedLabel(a, l, 3)),
            ("reflect y -> L - 1 - y", ReflectedLabel(a, l)),
            ("negate the configuration", NegationLabel(a, l)),
        };
    }

    public static bool NoOperationCollapsesTheSectorToZero()
        => OperationTable().All(t => Math.Abs(t.Label) > 0.5);

    public static string[] OperationsThatChangeTheLabel()
        => OperationTable().Where(t => Math.Abs(t.Label - 1.0) > 0.5).Select(t => t.Operation).ToArray();

    // ===================== 5. THE CANDIDATES =====================

    public static (string Candidate, string Status, string Basis)[] Candidates() => new[]
    {
        ("boundary conditions", "BOUNDARY",
            "the assignment is the origin: one operation generates the family "
            + $"({string.Join(", ", VacuumToSectorSeries().Select(t => $"{t.Label:F0}") )}) and no AT law depends on it "
            + $"(blindness residual {SectorBlindnessResidual():E3})"),
        ("topological constraints", "REFUTED",
            $"E_012's constraint permits EVERY sector: residual "
            + $"{string.Join(", ", ConstraintAcrossSectors().Select(t => $"{t.Residual:E0} for n = {t.N}"))}"),
        ("actualization process", "REFUTED",
            $"the update rule is purely electric - max |F_ij| = {CouplingFunctionAudit.DerivedSectorSplit().Magnetic:E3} "
            + $"- so it cannot weight a spatial sector at all (E_009, E_013)"),
        ("initial conditions", "BOUNDARY",
            "the same origin under another name: WHEN the assignment is made is not a different mechanism from WHERE; "
            + "recorded as a degeneracy rather than resolved"),
        ("occupancy arrangement", "REFUTED",
            $"sector-blind through linearity - the occupancy contribution is "
            + $"{OccupancyContributionToCurvature(0, 8):E3} at n = 0 against {OccupancyContributionToCurvature(1, 8):E3} "
            + $"at n = 1 - and it scales away as a^{FluxExcitationAudit.OccupancyScalingExponent():F2}"),
    };

    public static string[] RefutedCandidates()
        => Candidates().Where(c => c.Status == "REFUTED").Select(c => c.Candidate).ToArray();

    public static string[] BoundaryCandidates()
        => Candidates().Where(c => c.Status == "BOUNDARY").Select(c => c.Candidate).ToArray();

    public static string TheOriginOfSectorOccupation() => "an external assignment";

    // ===================== 6. THE REQUIREMENTS =====================

    public static (string Requirement, string Status)[] RequirementCheck() => new[]
    {
        ("n exists", $"read as the uniform strength in quanta: {SectorLabel(UniformSector(2, 16), 16):F6} for n = 2, "
            + $"uniform to {UniformityResidual(UniformSector(2, 16), 16):E3}"),
        ("n is quantised", $"the shift moves the label by {ShiftMovesTheLabelByOne(0, 16)} and the phase is periodic "
            + $"to {ShiftPhasePeriodicityResidual():E3} while the real field is not ({ShiftRealPeriodicityResidual():F3})"),
        ("n survives refinement", $"the label reads "
            + string.Join(", ", LabelSurvivesRefinement().Select(t => $"{t.Label:F0} at L = {t.L}"))
            + $", with the strength falling as {LabelSurvivesRefinement()[0].Strength / LabelSurvivesRefinement()[^1].Strength:F1}x"),
        ("why n != 0 is unanswered inside AT", $"no law depends on the sector ({EveryATLawIsSectorBlind()}), the "
            + $"constraint permits every value ({TheConstraintPermitsEverySector()}), and no operation takes a non-zero "
            + $"label to zero ({NoOperationCollapsesTheSectorToZero()})"),
    };

    // ===================== 7. VERDICT =====================

    /// <summary>
    /// The verdict is computed and has a live branch: a sector-DEPENDENT AT law would make the occupation derivable.
    /// </summary>
    public static string Verdict()
    {
        if (!EveryATLawIsSectorBlind()) return "DERIVED";          // something in AT weights the sector
        if (!TheConstraintPermitsEverySector()) return "DERIVED";  // a constraint selects a value
        if (!NoOperationCollapsesTheSectorToZero()) return "DERIVED";
        if (!OneOperationGeneratesTheFamily()) return "REFUTED";   // the label is not even well defined
        if (Control_TheSectorIsVisible() < 0.5) return "REFUTED";
        return "BOUNDARY";
    }

    public static string WhereItStands()
        => "THE SECTOR IS NOT SELECTED INSIDE AT, AND THE AUDIT PROVES THE NEGATIVE RATHER THAN DECLARING IT. E_011 "
         + "quantised the flux and called the integer a label; E_012 constrained which patterns are allowed; E_013 "
         + "showed that any populating move must be a pair and that nothing makes one. This audit asks the remaining "
         + "question - why is the label non-zero - and answers it with four measurements, each of which closes a door. "
         + "FIRST, THE FAMILY IS GENERATED BY ONE OPERATION, AND THAT OPERATION IS AN ASSIGNMENT. Adding a single "
         + "quantum of uniform field, A_1 -> A_1 + (2 pi / L) y, is a legitimate change of a COMPACT phase: the real "
         + $"field at the far end is {ShiftRealPeriodicityResidual():F3}, not zero, but the phase is the same to "
         + $"{ShiftPhasePeriodicityResidual():E3} - which is exactly how E_011's quantisation arose. Applied to the "
         + $"vacuum it produces the whole family, {string.Join(", ", VacuumToSectorSeries().Select(t => $"{t.Label:F0}"))}, "
         + $"with the strength following 2 pi n / L, and it inverts to {ShiftInvertibilityResidual():E3}. So the sectors "
         + "are one orbit under an assignment, not a family the dynamics wanders through. A note on the reading: the "
         + "label is taken from the REDUCED plaquette, so the seam cell is read as the same phase as every other cell - "
         + "without that reduction a uniform sector looks non-uniform at the wrap-around, which is the same seam that "
         + "E_012 and E_013 each had to handle. SECOND, NOTHING IN AT DEPENDS "
         + "ON THE SECTOR, and the measurement is made through linearity rather than asserted: the occupancy's own "
         + $"curvature contribution is {OccupancyContributionToCurvature(0, 8):E3} in the trivial sector and "
         + $"{OccupancyContributionToCurvature(1, 8):E3} in the unit sector - identical, as it must be, because the link "
         + "field of the organisation is built from the organisation alone and the curvature is additive. The update "
         + "rule's two parts and the clock law read identically as well, giving a blindness residual of "
         + $"{SectorBlindnessResidual():E3} against a control of {Control_TheSectorIsVisible():F1} which shows the sector "
         + "is visible to a curvature measurement whenever one wants to see it. A theory with no potential for a label "
         + "has no way to prefer a value of that label. THIRD, THE CONSTRAINT PERMITS EVERY SECTOR, so no selection "
         + "argument can be built on it: E_012's whole-torus residual is at machine precision for every integer tested - "
         + string.Join(", ", ConstraintAcrossSectors().Select(t => $"n = {t.N}"));
    public static string WhereItStandsTail()
        => $"{ConstraintAcrossSectors().All(t => t.Residual < 1e-12)} - and the constraint that FORBIDS the single "
         + "fluxon therefore does not restrict the uniform family at all. FOURTH, NO SYMMETRY COLLAPSES A NON-ZERO "
         + "SECTOR TO ZERO, which is the sharpest way to say that n = 0 is not special either. Measuring the operations "
         + "the configuration space actually has: translation preserves the label "
         + $"({string.Join(", ", OperationTable().Take(3).Select(t => $"{t.Operation} -> {t.Label:F0}"))}), reflection "
         + $"reverses it - {OperationTable()[3].Label:F0}, the orientation being reversed - and negation reverses it too, "
         + $"at {OperationTable()[4].Label:F0}. Nothing produces zero. So the question WHY N != 0 has exactly the same "
         + "status as WHY N = 0: neither is selected, and the label is generated by an assignment that comes from "
         + "outside the theory. THE CANDIDATES SORT ACCORDINGLY. Topological constraints are refuted, because the "
         + "constraint permits every value. The actualization process is refuted, because its field strength is purely "
         + "electric and cannot weight a spatial sector. Occupancy arrangement is refuted twice over: sector-blind "
         + "through linearity, and scaling away as a squared lattice spacing. What remains is boundary conditions and "
         + "initial conditions, and they are the SAME origin under two names - WHEN the assignment is made is not a "
         + "different mechanism from WHERE - a degeneracy this audit records rather than resolves. SO THE ORIGIN OF "
         + "SECTOR OCCUPATION IS AN EXTERNAL ASSIGNMENT, and what AT derives is the label and its quantisation: n is a "
         + "BOUNDARY in the precise sense the programme has been using, and the audit's own verdict has a live branch - "
         + "a single sector-dependent law anywhere in AT would move it to DERIVED.";

    // ===================== REPORT =====================

    public static string OutputTheLabel()
    {
        var sb = new StringBuilder();
        sb.AppendLine("1. THE LABEL AND THE ONE OPERATION THAT GENERATES THE FAMILY");
        sb.AppendLine($"   label at L = 8/16/32/64 for n = 1 : "
            + string.Join(", ", LabelSurvivesRefinement().Select(t => $"{t.Label:F0}")));
        sb.AppendLine($"   strength at L = 8/16/32/64         : "
            + string.Join(", ", LabelSurvivesRefinement().Select(t => $"{t.Strength:F6}")));
        sb.AppendLine($"   vacuum to sector series            : "
            + string.Join(" -> ", VacuumToSectorSeries().Select(t => $"{t.Label:F0}")));
        sb.AppendLine($"   shift moves the label by           : {ShiftMovesTheLabelByOne(0, 16)}");
        sb.AppendLine($"   phase periodicity residual         : {ShiftPhasePeriodicityResidual():E3}  (real field: {ShiftRealPeriodicityResidual():F3}, not periodic)");
        sb.AppendLine($"   shift invertibility residual       : {ShiftInvertibilityResidual():E3}");
        sb.AppendLine($"   uniformity residual                : {UniformityResidual(UniformSector(2, 16), 16):E3}");
        return sb.ToString();
    }

    public static string OutputBlindness()
    {
        var sb = new StringBuilder();
        sb.AppendLine("2. NOTHING IN AT DEPENDS ON THE SECTOR - MEASURED THROUGH LINEARITY");
        sb.AppendLine("   law                                 | at n = 0   | at n = 1   | difference");
        foreach (var (law, zero, one, diff) in SectorBlindnessTable())
            sb.AppendLine($"   {law,-35} | {zero,10:E2} | {one,10:E2} | {diff,10:E2}");
        sb.AppendLine($"   blindness residual                  : {SectorBlindnessResidual():E3}");
        sb.AppendLine($"   control: the sector is visible as   : {Control_TheSectorIsVisible():F6} quanta");
        sb.AppendLine();
        sb.AppendLine("3. THE CONSTRAINT PERMITS EVERY SECTOR");
        foreach (var (n, residual) in ConstraintAcrossSectors())
            sb.AppendLine($"   n = {n,2} : whole-torus residual {residual:E3}");
        return sb.ToString();
    }

    public static string OutputOperations()
    {
        var sb = new StringBuilder();
        sb.AppendLine("4. NO OPERATION TAKES A NON-ZERO LABEL TO ZERO");
        sb.AppendLine("   operation                    | label produced from n = 1");
        foreach (var (operation, label) in OperationTable())
            sb.AppendLine($"   {operation,-28} | {label,8:F6}");
        sb.AppendLine($"   operations that change the label : {string.Join(", ", OperationsThatChangeTheLabel())}");
        sb.AppendLine($"   none collapses it to zero        : {NoOperationCollapsesTheSectorToZero()}");
        return sb.ToString();
    }

    public static string OutputCandidates()
    {
        var sb = new StringBuilder();
        sb.AppendLine("5. THE CANDIDATES");
        foreach (var (candidate, status, basis) in Candidates())
        {
            sb.AppendLine($"   {candidate}");
            sb.AppendLine($"     -> {status}: {basis}");
        }
        sb.AppendLine();
        sb.AppendLine("6. WHAT IS KNOWN AND WHAT IS NOT");
        foreach (var (requirement, status) in RequirementCheck())
            sb.AppendLine($"   {requirement,-32} : {status}");
        return sb.ToString();
    }

    public static string OutputVerdict()
    {
        var sb = new StringBuilder();
        sb.AppendLine("7. VERDICT");
        sb.AppendLine(Verdict());
        sb.AppendLine($"   the origin of sector occupation : {TheOriginOfSectorOccupation()}");
        sb.AppendLine($"   refuted                         : {string.Join(", ", RefutedCandidates())}");
        sb.AppendLine($"   boundary                        : {string.Join(", ", BoundaryCandidates())}");
        sb.AppendLine();
        sb.AppendLine(WhereItStands());
        sb.AppendLine(WhereItStandsTail());
        return sb.ToString();
    }
}
